[core]
	engine = pg
	plan_file = sqitch.plan
	top_dir = .

# Define the parameter for the database engine
[engine "pg"]
	target = local
	registry = sqitch
	# client = psql

# Define a local migration environment 
[target "local"]

# Define a production migration environment
[target "prod"]
