-- Deploy ff2b_db:appschema to pg

CREATE TYPE "licence_status" AS ENUM (
	'brouillon',
	'demandée',
	'en attente',
	'validée',
	'suspendue',
	'expirée',
	'annulée'
);

CREATE TYPE "contact_origin" AS ENUM (
	'internet',
	'IA',
	'téléphone',
	'email'
);

CREATE TYPE "seance_status" AS ENUM (
	'annulé',
	'reporté',
	'terminé',
	'en cours',
	'planifié'
);

CREATE TYPE "payments_method" AS ENUM (
	'carte_bancaire',
	'virement',
	'cheque',
	'especes',
	'pass_sport',
	'autre'
);

CREATE TYPE "payments_status" AS ENUM (
	'en_attente',
	'valide',
	'echoue',
	'rembourse',
	'annule'
);

CREATE TYPE "game_status" AS ENUM (
	'planned',
	'in_progress',
	'completed',
	'cancelled',
	'forfeited'
);

CREATE TABLE IF NOT EXISTS "persons" (
	-- Unique identifier for the person within the organization.
	"ff2b_id" UUID NOT NULL DEFAULT gen_random_uuid(),
	-- Person's first name.
	"first_name" TEXT NOT NULL,
	-- Person's last name.
	"last_name" TEXT NOT NULL,
	-- Person's date of birth.
	"birthdate" DATE NOT NULL,
	-- Person's phone number.
	"phone_number" TEXT NOT NULL,
	-- Email address.
	"email" TEXT NOT NULL,
	-- Status.
	"status" SMALLINT,
	-- Origin of the contact.
	"contact_origin" contact_origin,
	-- Postal address.
	"address" VARCHAR(255),
	-- Identifier of the associated municipality.
	"municipality_id" INTEGER,
	-- Record creation timestamp.
	"creation_date" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("ff2b_id")
);

COMMENT ON COLUMN "persons"."ff2b_id" IS 'Unique identifier for the person within the organization.';
COMMENT ON COLUMN "persons"."first_name" IS 'Person''s first name.';
COMMENT ON COLUMN "persons"."last_name" IS 'Person''s last name.';
COMMENT ON COLUMN "persons"."birthdate" IS 'Person''s date of birth.';
COMMENT ON COLUMN "persons"."phone_number" IS 'Person''s phone number.';
COMMENT ON COLUMN "persons"."email" IS 'Email address.';
COMMENT ON COLUMN "persons"."status" IS 'Status.';
COMMENT ON COLUMN "persons"."contact_origin" IS 'Origin of the contact.';
COMMENT ON COLUMN "persons"."address" IS 'Postal address.';
COMMENT ON COLUMN "persons"."municipality_id" IS 'Identifier of the associated municipality.';
COMMENT ON COLUMN "persons"."creation_date" IS 'Record creation timestamp.';

CREATE TABLE IF NOT EXISTS "person_status" (
	--Unique identifier for this record.
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	-- Description.
	"description" TEXT,

	PRIMARY KEY("id")
);

COMMENT ON COLUMN "person_status"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "person_status"."code" IS 'Unique code.';
COMMENT ON COLUMN "person_status"."label" IS 'Display label.';
COMMENT ON COLUMN "person_status"."description" IS 'Description.';

CREATE TABLE IF NOT EXISTS "person_roles" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated role.
	"role_id" SMALLINT NOT NULL,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	PRIMARY KEY("id"),
	CONSTRAINT "person_role_unique_0" UNIQUE ("role_id", "person_id")
);

COMMENT ON COLUMN "person_roles"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "person_roles"."role_id" IS 'Identifier of the associated role.';
COMMENT ON COLUMN "person_roles"."person_id" IS 'Identifier of the associated person.';

CREATE TABLE IF NOT EXISTS "roles" (
	-- Unique identifier for this record.
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	-- Description.
	"description" TEXT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "roles"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "roles"."code" IS 'Unique code.';
COMMENT ON COLUMN "roles"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "licenses" (
	-- Unique identifier for this record.
	"id" UUID NOT NULL DEFAULT gen_random_uuid(),
	-- Identifier of the license type.
	"license_type" INTEGER NOT NULL,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Identifier of the associated season.
	"season_id" INTEGER NOT NULL,
	-- License request date.
	"request_date" DATE NOT NULL,
	-- License validation date.
	"validation_date" DATE,
	-- License start date.
	"beginning_date" DATE,
	-- End date.
	"end_date" DATE,
	-- License status.
	"license_status" licence_status NOT NULL,
	-- Identifier of the associated document.
	"document_id" UUID,
	PRIMARY KEY("id"),

	CONSTRAINT validation_date_check CHECK (
    "validation_date" IS NULL
    OR "validation_date" >= "request_date"
),
	CONSTRAINT end_date_check CHECK (
    "end_date" IS NULL
    OR "beginning_date" IS NULL
    OR "end_date" >= "beginning_date"
)
);

COMMENT ON COLUMN "licenses"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "licenses"."license_type" IS 'Identifier of the license type.';
COMMENT ON COLUMN "licenses"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "licenses"."season_id" IS 'Identifier of the associated season.';
COMMENT ON COLUMN "licenses"."request_date" IS 'License request date.';
COMMENT ON COLUMN "licenses"."validation_date" IS 'License validation date.';
COMMENT ON COLUMN "licenses"."beginning_date" IS 'License start date.';
COMMENT ON COLUMN "licenses"."end_date" IS 'End date.';
COMMENT ON COLUMN "licenses"."license_status" IS 'License status.';
COMMENT ON COLUMN "licenses"."document_id" IS 'Identifier of the associated document.';

CREATE TABLE IF NOT EXISTS "license_types" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- license code.
	"license_code" TEXT NOT NULL UNIQUE,
	-- license label.
	"license_label" TEXT NOT NULL UNIQUE,
	-- Description.
	"description" TEXT NULL,

	PRIMARY KEY("id")
);

COMMENT ON COLUMN "license_types"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "license_types"."license_code" IS 'license code.';
COMMENT ON COLUMN "license_types"."license_label" IS 'license label.';

CREATE TABLE IF NOT EXISTS "seasons" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Season start year.
	"start_year" SMALLINT NOT NULL,
	-- Season end year.
	"end_year" SMALLINT NOT NULL CHECK("end_year" = "start_year" + 1),
	PRIMARY KEY("id"),
	CONSTRAINT "seasons_unique_check" UNIQUE ("start_year", "end_year")
);

COMMENT ON COLUMN "seasons"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "seasons"."start_year" IS 'Season start year.';
COMMENT ON COLUMN "seasons"."end_year" IS 'Season end year.';

CREATE TABLE IF NOT EXISTS "municipalities" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Name.
	"name" TEXT NOT NULL,
	-- Postal code.
	"zip_code" TEXT NOT NULL,
	-- INSEE municipality code.
	"insee_code" VARCHAR(10),
	-- Identifier of the associated department.
	"departement_id" INTEGER NOT NULL,
	-- Municipality development status.
	"development_status" SMALLINT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "municipalities"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "municipalities"."name" IS 'Name.';
COMMENT ON COLUMN "municipalities"."zip_code" IS 'Postal code.';
COMMENT ON COLUMN "municipalities"."insee_code" IS 'INSEE municipality code.';
COMMENT ON COLUMN "municipalities"."departement_id" IS 'Identifier of the associated department.';
COMMENT ON COLUMN "municipalities"."development_status" IS 'Municipality development status.';

CREATE TABLE IF NOT EXISTS "development_status" (
	-- Unique identifier for this record
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code for the development status
	"code" TEXT NOT NULL UNIQUE,
	-- Unique label for the development status
	"label" TEXT NOT NULL UNIQUE,
	-- Description of the development status
	"description" TEXT,

	PRIMARY KEY("id")
);

COMMENT ON COLUMN "development_status"."id" IS 'Unique identifier for this record';
COMMENT ON COLUMN "development_status"."code" IS 'Unique code for the development status';
COMMENT ON COLUMN "development_status"."label" IS 'Unique label for the development status displayed in the app';
COMMENT ON COLUMN "development_status"."description" IS 'Description of the development status';

CREATE TABLE IF NOT EXISTS "departments" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Name.
	"name" TEXT NOT NULL,
	-- Unique code.
	"code" TEXT NOT NULL,
	-- Identifier of the associated region.
	"region_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "departments"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "departments"."name" IS 'Name.';
COMMENT ON COLUMN "departments"."code" IS 'Unique code.';
COMMENT ON COLUMN "departments"."region_id" IS 'Identifier of the associated region.';

CREATE TABLE IF NOT EXISTS "regions" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Name.
	"name" TEXT NOT NULL,
	-- Unique code.
	"code" TEXT,
	-- Identifier of the associated country.
	"country_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "regions"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "regions"."name" IS 'Name.';
COMMENT ON COLUMN "regions"."code" IS 'Unique code.';
COMMENT ON COLUMN "regions"."country_id" IS 'Identifier of the associated country.';

CREATE TABLE IF NOT EXISTS "countries" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Name.
	"name" TEXT NOT NULL,
	-- Unique code.
	"code" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "countries"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "countries"."name" IS 'Name.';
COMMENT ON COLUMN "countries"."code" IS 'Unique code.';

CREATE TABLE IF NOT EXISTS "practice_sites" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Name.
	"name" TEXT NOT NULL,
	-- Identifier of the associated municipality.
	"municipality_id" INTEGER NOT NULL,
	-- Postal address.
	"address" TEXT,
	-- Opening date.
	"opening_date" DATE,
	-- Closing date.
	"closing_date" DATE CHECK (
    closing_date IS NULL
    OR opening_date IS NULL
    OR closing_date >= opening_date
),
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "practice_sites"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "practice_sites"."name" IS 'Name.';
COMMENT ON COLUMN "practice_sites"."municipality_id" IS 'Identifier of the associated municipality.';
COMMENT ON COLUMN "practice_sites"."address" IS 'Postal address.';
COMMENT ON COLUMN "practice_sites"."opening_date" IS 'Opening date.';
COMMENT ON COLUMN "practice_sites"."closing_date" IS 'Closing date.';

CREATE TABLE IF NOT EXISTS "equipments" (

	--Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	--Identifier of the associated practice site.
	"practice_site_id" INTEGER,
	-- Name.
	"name" TEXT NOT NULL,
	-- Description.
    "description" TEXT,
	-- Identifier of the equipment category.
	"category_id" INTEGER NOT NULL,
	-- Identifier of the equipment status.
	"status_id" SMALLINT NOT NULL,
	-- Equipment quantity; defaults to 1.
	"quantity" INTEGER NOT NULL DEFAULT 1 CHECK ("quantity" >= 0),
	-- Purchase date.
    "purchase_date" DATE,
	-- Purchase price.
    "purchase_price" NUMERIC(8, 2) CHECK ("purchase_price" >= 0),
	-- Additional notes.
    "notes" TEXT,

	PRIMARY KEY("id")
);

COMMENT ON COLUMN "equipments"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "equipments"."practice_site_id" IS 'Identifier of the associated practice site.';
COMMENT ON COLUMN "equipments"."name" IS 'Name.';
COMMENT ON COLUMN "equipments"."description" IS 'Description.';
COMMENT ON COLUMN "equipments"."category_id" IS 'Identifier of the equipment category.';
COMMENT ON COLUMN "equipments"."status_id" IS 'Identifier of the equipment status.';
COMMENT ON COLUMN "equipments"."quantity" IS 'Equipment quantity; defaults to 1.';
COMMENT ON COLUMN "equipments"."purchase_date" IS 'Purchase date.';
COMMENT ON COLUMN "equipments"."purchase_price" IS 'Purchase price.';
COMMENT ON COLUMN "equipments"."notes" IS 'Additional notes.';


CREATE TABLE IF NOT EXISTS "equipment_categories" (

	-- Unique identifier for this record.
    "id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	--Unique code.
    "code" TEXT NOT NULL UNIQUE,
	-- Display label.
    "label" TEXT NOT NULL UNIQUE,
	-- Description.
	"description" TEXT,
    PRIMARY KEY("id")
);

COMMENT ON COLUMN "equipment_categories"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "equipment_categories"."code" IS 'Unique code.';
COMMENT ON COLUMN "equipment_categories"."label" IS 'Display label.';
COMMENT ON COLUMN "equipment_categories"."description" IS 'Description.';

CREATE TABLE IF NOT EXISTS "equipment_status" (

	-- Unique identifier for this record.
    "id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
    "code" TEXT NOT NULL UNIQUE,
	-- Display label.
    "label" TEXT NOT NULL UNIQUE,
    PRIMARY KEY("id")
);

COMMENT ON COLUMN "equipment_status"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "equipment_status"."code" IS 'Unique code of the equipment status.';
COMMENT ON COLUMN "equipment_status"."label" IS 'Display label of the equipment status.';

CREATE TABLE IF NOT EXISTS "slots" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated site.
	"site_id" INTEGER NOT NULL,
	-- Identifier of the associated season.
	"season_id" INTEGER NOT NULL,
	-- Start time.
	"start_at" TIME NOT NULL,
	-- End time.
	"end_at" TIME NOT NULL CHECK ("end_at" > "start_at"),
	-- Maximum capacity.
	"capacity" SMALLINT  CHECK ("capacity" >= 0),
	-- Day of the week, from 1 to 7.
	"day_of_week" SMALLINT CHECK(day_of_week BETWEEN 1 AND 7),
	PRIMARY KEY("id"),
	CONSTRAINT slots_unique_0 UNIQUE (
    "site_id",
    "season_id",
    "day_of_week",
    "start_at",
    "end_at"
)
);

COMMENT ON COLUMN "slots"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "slots"."site_id" IS 'Identifier of the associated site.';
COMMENT ON COLUMN "slots"."season_id" IS 'Identifier of the associated season.';
COMMENT ON COLUMN "slots"."start_at" IS 'Start time.';
COMMENT ON COLUMN "slots"."end_at" IS 'End time.';
COMMENT ON COLUMN "slots"."capacity" IS 'Maximum capacity.';
COMMENT ON COLUMN "slots"."day_of_week" IS 'Day of the week, from 1 to 7.';

CREATE TABLE IF NOT EXISTS "sessions" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated slot.
	"slot_id" INTEGER NOT NULL,
	-- Start time.
	"start_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Duration in minutes.
	"duration" SMALLINT NOT NULL  CHECK (duration > 0),
	-- Identifier of the associated referent.
	"referent_id" INTEGER,
	-- Identifier of the associated coach.
	"coach_id" UUID,
	-- Session content.
	"content" TEXT,
	-- Status.
	"status" seance_status,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "sessions"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "sessions"."slot_id" IS 'Identifier of the associated slot.';
COMMENT ON COLUMN "sessions"."start_at" IS 'Start time.';
COMMENT ON COLUMN "sessions"."duration" IS 'Duration in minutes.';
COMMENT ON COLUMN "sessions"."referent_id" IS 'Identifier of the associated referent.';
COMMENT ON COLUMN "sessions"."coach_id" IS 'Identifier of the associated coach.';
COMMENT ON COLUMN "sessions"."content" IS 'Session content.';
COMMENT ON COLUMN "sessions"."status" IS 'Status.';

CREATE TABLE IF NOT EXISTS "session_participants" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Identifier of the associated session.
	"session_id" INTEGER NOT NULL,
	-- Identifier of the associated license.
	"license_id" UUID NOT NULL,
	-- Whether the person was present.
	"presence" BOOLEAN NULL,
	PRIMARY KEY("id"),
	CONSTRAINT "session_participants_unique_0" UNIQUE ("person_id", "session_id")
);

COMMENT ON COLUMN "session_participants"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "session_participants"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "session_participants"."session_id" IS 'Identifier of the associated session.';
COMMENT ON COLUMN "session_participants"."license_id" IS 'Identifier of the associated license.';
COMMENT ON COLUMN "session_participants"."presence" IS 'Whether the person was present.';

CREATE TABLE IF NOT EXISTS "competitions" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated season.
	"season_id" INTEGER NOT NULL,
	-- Event date.
	"date" DATE NOT NULL,
	-- Identifier of the location.
	"location_id" INTEGER NOT NULL,
	-- Identifier of the associated practice site.
	"practice_site_id" INTEGER NOT NULL,
	-- Identifier of the organizer.
	"organizer_id" UUID NOT NULL,
	-- Identifier of the associated format.
	"format_id" SMALLINT NOT NULL,
	-- Status.
	"status" INTEGER,
	-- Identifier of the rules document.
	"rules_document_id" UUID,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competitions"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "competitions"."season_id" IS 'Identifier of the associated season.';
COMMENT ON COLUMN "competitions"."date" IS 'Event date.';
COMMENT ON COLUMN "competitions"."location_id" IS 'Identifier of the location.';
COMMENT ON COLUMN "competitions"."practice_site_id" IS 'Identifier of the associated practice site.';
COMMENT ON COLUMN "competitions"."organizer_id" IS 'Identifier of the organizer.';
COMMENT ON COLUMN "competitions"."format_id" IS 'Identifier of the associated format.';
COMMENT ON COLUMN "competitions"."status" IS 'Status.';
COMMENT ON COLUMN "competitions"."rules_document_id" IS 'Identifier of the rules document.';

CREATE TABLE IF NOT EXISTS "competition_formats" (
	-- Unique identifier for this record.
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competition_formats"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "competition_formats"."code" IS 'Unique code.';
COMMENT ON COLUMN "competition_formats"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "competition_status" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competition_status"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "competition_status"."code" IS 'Unique code.';
COMMENT ON COLUMN "competition_status"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "competition_participant" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated competition.
	"competition_id" INTEGER NOT NULL,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Status.
	"status" INTEGER NOT NULL,
	-- category.
	"category" INTEGER NOT NULL,
	-- Identifier of the associated license.
	"license_id" UUID NOT NULL,
	-- Ranking before the event.
	"ranking_before" SMALLINT,
	-- Ranking after the event.
	"ranking_after" SMALLINT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competition_participant"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "competition_participant"."competition_id" IS 'Identifier of the associated competition.';
COMMENT ON COLUMN "competition_participant"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "competition_participant"."status" IS 'Status.';
COMMENT ON COLUMN "competition_participant"."category" IS 'category.';
COMMENT ON COLUMN "competition_participant"."license_id" IS 'Identifier of the associated license.';
COMMENT ON COLUMN "competition_participant"."ranking_before" IS 'Ranking before the event.';
COMMENT ON COLUMN "competition_participant"."ranking_after" IS 'Ranking after the event.';

CREATE TABLE IF NOT EXISTS "competition_participant_status" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competition_participant_status"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "competition_participant_status"."code" IS 'Unique code.';
COMMENT ON COLUMN "competition_participant_status"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "competition_participant_category" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competition_participant_category"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "competition_participant_category"."code" IS 'Unique code.';
COMMENT ON COLUMN "competition_participant_category"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "games" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated competition.
	"competition_id" INTEGER,
	-- Identifier of the associated format.
	"format_id" SMALLINT NOT NULL,
	-- Event date.
	"date" TIMESTAMPTZ NOT NULL,
	-- Current lifecycle status of the game.
	"status" game_status NOT NULL DEFAULT 'planned',
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "games"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "games"."competition_id" IS 'Identifier of the associated competition.';
COMMENT ON COLUMN "games"."format_id" IS 'Identifier of the associated format.';
COMMENT ON COLUMN "games"."date" IS 'Event date.';
COMMENT ON COLUMN "games"."status" IS 'Current lifecycle status of the game.';

CREATE TABLE IF NOT EXISTS "game_format" (
	-- Unique identifier for this record.
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "game_format"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "game_format"."code" IS 'Unique code.';
COMMENT ON COLUMN "game_format"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "game_participant" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated game side.
	"game_side_id" INTEGER NOT NULL,
	-- Ranking before the event.
	"ranking_before" SMALLINT NOT NULL CHECK ("ranking_before" >= 0),
	-- Ranking after the event.
	"ranking_after" SMALLINT CHECK ("ranking_after" IS NULL OR "ranking_after" >= 0),
	-- ELO rating before the game.
	"elo_before" SMALLINT CHECK ("elo_before" > 0),
	-- ELO rating after the game.
	"elo_after" SMALLINT  CHECK ("elo_after" > 0),
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,

	

	PRIMARY KEY("id")
);

COMMENT ON COLUMN "game_participant"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "game_participant"."game_side_id" IS 'Identifier of the associated game side.';
COMMENT ON COLUMN "game_participant"."ranking_before" IS 'Ranking before the event.';
COMMENT ON COLUMN "game_participant"."ranking_after" IS 'Ranking after the event.';
COMMENT ON COLUMN "game_participant"."elo_before" IS 'ELO rating before the game.';
COMMENT ON COLUMN "game_participant"."elo_after" IS 'ELO rating after the game.';
COMMENT ON COLUMN "game_participant"."person_id" IS 'Identifier of the associated person.';

CREATE TABLE IF NOT EXISTS "game_side" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated game.
	"game_id" INTEGER NOT NULL,
	-- Game side number, either 1 or 2.
	"side_number" SMALLINT NOT NULL CHECK("side_number" IN (1, 2)),
	"person_id" UUID,
    "team_id" INTEGER,


	PRIMARY KEY("id"),
	CONSTRAINT "game_side_unique_0" UNIQUE ("game_id", "side_number"),
	CONSTRAINT game_side_participant_check
        CHECK (
            (person_id IS NOT NULL AND team_id IS NULL)
            OR
            (person_id IS NULL AND team_id IS NOT NULL)
        )
);

COMMENT ON COLUMN "game_side"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "game_side"."game_id" IS 'Identifier of the associated game.';
COMMENT ON COLUMN "game_side"."side_number" IS 'Game side number, either 1 or 2.';

CREATE TABLE IF NOT EXISTS "game_side_result" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated game side.
	"game_side_id" INTEGER NOT NULL UNIQUE,
	-- Number of nieshs scored.
	"nieshs_scored" SMALLINT NOT NULL CHECK ("nieshs_scored" >= 0),
	-- Number of nieshs conceded.
	"nieshs_conceded" SMALLINT NOT NULL CHECK ("nieshs_conceded" >= 0),
	-- Result for this game side.
	"result" SMALLINT GENERATED ALWAYS AS (
		CASE
			WHEN "nieshs_scored" > "nieshs_conceded" THEN 1
			WHEN "nieshs_scored" = "nieshs_conceded" THEN 2
			ELSE 3
		END
	) STORED,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "game_side_result"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "game_side_result"."game_side_id" IS 'Identifier of the associated game side.';
COMMENT ON COLUMN "game_side_result"."nieshs_scored" IS 'Number of nieshs scored.';
COMMENT ON COLUMN "game_side_result"."nieshs_conceded" IS 'Number of nieshs conceded.';
COMMENT ON COLUMN "game_side_result"."result" IS 'Generated result: 1 = win, 2 = draw, 3 = loss.';

CREATE TABLE IF NOT EXISTS "teams" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated competition.
	"competition_id" INTEGER NOT NULL,
	-- Name.
	"name" TEXT NOT NULL,
	PRIMARY KEY("id"),
	CONSTRAINT "teams_unique_0" UNIQUE ("competition_id", "name")
);

COMMENT ON COLUMN "teams"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "teams"."competition_id" IS 'Identifier of the associated competition.';
COMMENT ON COLUMN "teams"."name" IS 'Name.';

CREATE TABLE IF NOT EXISTS "team_members" (
	-- Identifier of the associated team.
	"team_id" INTEGER NOT NULL,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	PRIMARY KEY("team_id", "person_id")
);

COMMENT ON COLUMN "team_members"."team_id" IS 'Identifier of the associated team.';
COMMENT ON COLUMN "team_members"."person_id" IS 'Identifier of the associated person.';

CREATE TABLE IF NOT EXISTS "referents" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Identifier of the associated site.
	"site_id" INTEGER NOT NULL,
	-- Start date.
	"start_date" DATE NOT NULL,
	-- End date.
	"end_date" DATE CHECK (
    "end_date" IS NULL
    OR "end_date" >= "start_date"
),
	-- Professional phone number.
	"professional_phone" TEXT NOT NULL,
	-- Professional email address.
	"professional_mail" TEXT NOT NULL,
	-- Status.
	"status" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "referents"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "referents"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "referents"."site_id" IS 'Identifier of the associated site.';
COMMENT ON COLUMN "referents"."start_date" IS 'Start date.';
COMMENT ON COLUMN "referents"."end_date" IS 'End date.';
COMMENT ON COLUMN "referents"."professional_phone" IS 'Professional phone number.';
COMMENT ON COLUMN "referents"."professional_mail" IS 'Professional email address.';
COMMENT ON COLUMN "referents"."status" IS 'Status.';

CREATE TABLE IF NOT EXISTS "referent_status" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL,
	-- Display label.
	"label" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "referent_status"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "referent_status"."code" IS 'Unique code.';
COMMENT ON COLUMN "referent_status"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "volunteers" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Identifier of the manager.
	"manager_id" UUID NOT NULL,
	-- Mission to be performed.
	"mission" TEXT,
	-- Skills.
	"skills" TEXT,
	-- Availability.
	"availability" TEXT,
	-- Volunteer location.
	"location" INTEGER NOT NULL,
	-- Volunteer application date.
	"application_date" DATE,
	-- Observations.
	"observations" TEXT,
	-- Start date.
	"start_date" DATE NOT NULL,
	-- End date.
	"end_date" DATE CHECK (
    "end_date" IS NULL
    OR "end_date" >= "start_date"
),
	-- Tasks performed.
	"tasks" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "volunteers"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "volunteers"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "volunteers"."manager_id" IS 'Identifier of the manager.';
COMMENT ON COLUMN "volunteers"."mission" IS 'Mission to be performed.';
COMMENT ON COLUMN "volunteers"."skills" IS 'Skills.';
COMMENT ON COLUMN "volunteers"."availability" IS 'Availability.';
COMMENT ON COLUMN "volunteers"."location" IS 'Volunteer location.';
COMMENT ON COLUMN "volunteers"."application_date" IS 'Volunteer application date.';
COMMENT ON COLUMN "volunteers"."observations" IS 'Observations.';
COMMENT ON COLUMN "volunteers"."start_date" IS 'Start date.';
COMMENT ON COLUMN "volunteers"."end_date" IS 'End date.';
COMMENT ON COLUMN "volunteers"."tasks" IS 'Tasks performed.';

CREATE TABLE IF NOT EXISTS "organizations" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Name.
	"name" TEXT NOT NULL,
	-- Identifier of the organization type.
	"organization_type_id" SMALLINT NOT NULL,
	-- Identifier of the associated municipality.
	"municipality_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "organizations"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "organizations"."name" IS 'Name.';
COMMENT ON COLUMN "organizations"."organization_type_id" IS 'Identifier of the organization type.';
COMMENT ON COLUMN "organizations"."municipality_id" IS 'Identifier of the associated municipality.';

CREATE TABLE IF NOT EXISTS "organization_types" (
	-- Unique identifier for this record.
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL,
	-- Display label.
	"label" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "organization_types"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "organization_types"."code" IS 'Unique code.';
COMMENT ON COLUMN "organization_types"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "organizations_contact" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated organization.
	"organization_id" INTEGER NOT NULL,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Contact person's function.
	"function" TEXT,
	-- Start date.
	"start_date" DATE,
	-- End date.
	"end_date" DATE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "organizations_contact"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "organizations_contact"."organization_id" IS 'Identifier of the associated organization.';
COMMENT ON COLUMN "organizations_contact"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "organizations_contact"."function" IS 'Contact person''s function.';
COMMENT ON COLUMN "organizations_contact"."start_date" IS 'Start date.';
COMMENT ON COLUMN "organizations_contact"."end_date" IS 'End date.';

CREATE TABLE IF NOT EXISTS "prospects" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated person.
	"person_id" UUID,
	-- Identifier of the associated organization.
	"organization_id" INTEGER,
	-- type.
	"type" TEXT,
	-- Status.
	"status" TEXT,
	-- interest.
	"interest" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "prospects"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "prospects"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "prospects"."organization_id" IS 'Identifier of the associated organization.';
COMMENT ON COLUMN "prospects"."type" IS 'type.';
COMMENT ON COLUMN "prospects"."status" IS 'Status.';
COMMENT ON COLUMN "prospects"."interest" IS 'interest.';

CREATE TABLE IF NOT EXISTS "contacts" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated person.
	"person_id" UUID,
	-- Identifier of the associated organization.
	"organization_id" INTEGER,
	-- Contact timestamp.
	"contact_at" TIMESTAMPTZ,
	-- Identifier of the responsible person.
	"responsible_id" UUID NOT NULL,
	-- Contact subject.
	"subject" TEXT,
	-- Additional notes.
	"notes" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "contacts"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "contacts"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "contacts"."organization_id" IS 'Identifier of the associated organization.';
COMMENT ON COLUMN "contacts"."contact_at" IS 'Contact timestamp.';
COMMENT ON COLUMN "contacts"."responsible_id" IS 'Identifier of the responsible person.';
COMMENT ON COLUMN "contacts"."subject" IS 'Contact subject.';
COMMENT ON COLUMN "contacts"."notes" IS 'Additional notes.';

CREATE TABLE IF NOT EXISTS "users" (
	-- Unique identifier for this record.
	"id" UUID NOT NULL  DEFAULT gen_random_uuid(),
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL UNIQUE,
	-- Email address.
	"email" TEXT NOT NULL UNIQUE,
	-- Hashed password.
	"password" TEXT NOT NULL,
	-- Account status.
	"statut" SMALLINT,
	-- Record creation timestamp.
	"creation_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "users"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "users"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "users"."email" IS 'Email address.';
COMMENT ON COLUMN "users"."password" IS 'Hashed password.';
COMMENT ON COLUMN "users"."statut" IS 'Account status.';
COMMENT ON COLUMN "users"."creation_date" IS 'Record creation timestamp.';

CREATE TABLE IF NOT EXISTS "access_roles" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	-- Description.
	"description" TEXT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "access_roles"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "access_roles"."code" IS 'Unique code.';
COMMENT ON COLUMN "access_roles"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "users_roles" (
	-- Identifier of the associated role.
	"role_id" INTEGER NOT NULL,
	-- Identifier of the associated user.
	"user_id" UUID NOT NULL,
	PRIMARY KEY("role_id", "user_id")

);

COMMENT ON COLUMN "users_roles"."role_id" IS 'Identifier of the associated role.';
COMMENT ON COLUMN "users_roles"."user_id" IS 'Identifier of the associated user.';

CREATE TABLE IF NOT EXISTS "consents" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Identifier of the consent type.
	"consent_type_id" INTEGER NOT NULL,
	-- Date and time consent was given.
	"given_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Whether consent was accepted.
	"is_accepted" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "consents"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "consents"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "consents"."consent_type_id" IS 'Identifier of the consent type.';
COMMENT ON COLUMN "consents"."given_at" IS 'Date and time consent was given.';
COMMENT ON COLUMN "consents"."is_accepted" IS 'Whether consent was accepted.';

CREATE TABLE IF NOT EXISTS "consents_type" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL,
	-- Description.
	"description" TEXT,
	-- Whether consent is mandatory for registration.
	"is_mandatory" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "consents_type"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "consents_type"."code" IS 'Unique code.';
COMMENT ON COLUMN "consents_type"."label" IS 'Display label.';
COMMENT ON COLUMN "consents_type"."description" IS 'Description.';
COMMENT ON COLUMN "consents_type"."is_mandatory" IS 'Whether consent is mandatory for registration.';

CREATE TABLE IF NOT EXISTS "documents" (
	-- Unique identifier for this record.
	"id" UUID NOT NULL DEFAULT gen_random_uuid(),
	-- File name.
	"filename" TEXT NOT NULL,
	-- Storage path.
	"storage_path" TEXT NOT NULL,
	-- Identifier of the document type.
	"document_type_id" SMALLINT NOT NULL,
	-- Record creation timestamp.
	"creation_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Document media type.
	"mime_type" VARCHAR(40),
	-- File size in bytes.
	"file_size" INTEGER NOT NULL,
	-- File content hash.
	"hash" VARCHAR(64) NOT NULL CHECK ("hash" ~ '^[0-9a-fA-F]{64}$'),
	-- Identifier of the person who uploaded the file.
	"uploaded_by" UUID,
	-- Document expiration timestamp.
	"expires_at" TIMESTAMPTZ,
	PRIMARY KEY("id"),

	CONSTRAINT file_size_check CHECK ("file_size" >= 0)
);

COMMENT ON COLUMN "documents"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "documents"."filename" IS 'File name.';
COMMENT ON COLUMN "documents"."storage_path" IS 'Storage path.';
COMMENT ON COLUMN "documents"."document_type_id" IS 'Identifier of the document type.';
COMMENT ON COLUMN "documents"."creation_date" IS 'Record creation timestamp.';
COMMENT ON COLUMN "documents"."mime_type" IS 'Document media type.';
COMMENT ON COLUMN "documents"."file_size" IS 'File size in bytes.';
COMMENT ON COLUMN "documents"."hash" IS 'File content hash.';
COMMENT ON COLUMN "documents"."uploaded_by" IS 'Identifier of the person who uploaded the file.';
COMMENT ON COLUMN "documents"."expires_at" IS 'Document expiration timestamp.';

CREATE TABLE IF NOT EXISTS "document_types" (
	-- Unique identifier for this record.
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- document code.
	"document_code" TEXT NOT NULL UNIQUE,
	-- document label.
	"document_label" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "document_types"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "document_types"."document_code" IS 'document code.';
COMMENT ON COLUMN "document_types"."document_label" IS 'document label.';

CREATE TABLE IF NOT EXISTS "documents_persons" (
	-- Identifier of the associated document.
	"document_id" UUID NOT NULL,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	PRIMARY KEY("document_id", "person_id")
);

COMMENT ON COLUMN "documents_persons"."document_id" IS 'Identifier of the associated document.';
COMMENT ON COLUMN "documents_persons"."person_id" IS 'Identifier of the associated person.';

CREATE TABLE IF NOT EXISTS "documents_competitions" (
	-- Identifier of the associated document.
	"document_id" UUID NOT NULL,
	-- Identifier of the associated competition.
	"competition_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "competition_id")
);

COMMENT ON COLUMN "documents_competitions"."document_id" IS 'Identifier of the associated document.';
COMMENT ON COLUMN "documents_competitions"."competition_id" IS 'Identifier of the associated competition.';

CREATE TABLE IF NOT EXISTS "documents_licenses" (
	-- Identifier of the associated document.
	"document_id" UUID NOT NULL,
	-- Identifier of the associated license.
	"license_id" UUID NOT NULL,
	PRIMARY KEY("document_id", "license_id")
);

COMMENT ON COLUMN "documents_licenses"."document_id" IS 'Identifier of the associated document.';
COMMENT ON COLUMN "documents_licenses"."license_id" IS 'Identifier of the associated license.';

CREATE TABLE IF NOT EXISTS "documents_projects" (
	-- Identifier of the associated document.
	"document_id" UUID NOT NULL,
	-- Identifier of the associated project.
	"project_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "project_id")
);

COMMENT ON COLUMN "documents_projects"."document_id" IS 'Identifier of the associated document.';
COMMENT ON COLUMN "documents_projects"."project_id" IS 'Identifier of the associated project.';

CREATE TABLE IF NOT EXISTS "documents_commissions" (
	-- Identifier of the associated document.
	"document_id" UUID NOT NULL,
	-- Identifier of the associated commission.
	"commission_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "commission_id")
);

COMMENT ON COLUMN "documents_commissions"."document_id" IS 'Identifier of the associated document.';
COMMENT ON COLUMN "documents_commissions"."commission_id" IS 'Identifier of the associated commission.';

CREATE TABLE IF NOT EXISTS "documents_organizations" (
	-- Identifier of the associated document.
	"document_id" UUID NOT NULL,
	-- Identifier of the associated organization.
	"organization_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "organization_id")
);

COMMENT ON COLUMN "documents_organizations"."document_id" IS 'Identifier of the associated document.';
COMMENT ON COLUMN "documents_organizations"."organization_id" IS 'Identifier of the associated organization.';

CREATE TABLE IF NOT EXISTS "documents_practices_sites" (
	-- Identifier of the associated document.
	"document_id" UUID NOT NULL,
	-- Identifier of the associated practice site.
	"practice_site_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "practice_site_id")
);

COMMENT ON COLUMN "documents_practices_sites"."document_id" IS 'Identifier of the associated document.';
COMMENT ON COLUMN "documents_practices_sites"."practice_site_id" IS 'Identifier of the associated practice site.';

CREATE TABLE IF NOT EXISTS "projects" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Name.
	"name" TEXT NOT NULL,
	-- Description.
	"description" TEXT,
	-- Status.
	"status" SMALLINT NOT NULL,
	-- Start date.
	"start_date" DATE NOT NULL,
	-- End date.
	"end_date" DATE CHECK (
    "end_date" IS NULL
    OR "end_date" >= "start_date"
),
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "projects"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "projects"."name" IS 'Name.';
COMMENT ON COLUMN "projects"."description" IS 'Description.';
COMMENT ON COLUMN "projects"."status" IS 'Status.';
COMMENT ON COLUMN "projects"."start_date" IS 'Start date.';
COMMENT ON COLUMN "projects"."end_date" IS 'End date.';

CREATE TABLE IF NOT EXISTS "projects_members" (
	-- Identifier of the associated project.
	"project_id" INTEGER NOT NULL,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Identifier of the project role.
	"project_role" INTEGER NOT NULL,
	-- Date when the member joined.
	"joined_at" DATE,
	PRIMARY KEY("project_id", "person_id")
);

COMMENT ON COLUMN "projects_members"."project_id" IS 'Identifier of the associated project.';
COMMENT ON COLUMN "projects_members"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "projects_members"."project_role" IS 'Identifier of the project role.';
COMMENT ON COLUMN "projects_members"."joined_at" IS 'Date when the member joined.';

CREATE TABLE IF NOT EXISTS "projects_members_role" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "projects_members_role"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "projects_members_role"."code" IS 'Unique code.';
COMMENT ON COLUMN "projects_members_role"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "projects_status" (
	-- Unique identifier for this record.
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "projects_status"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "projects_status"."code" IS 'Unique code.';
COMMENT ON COLUMN "projects_status"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "commissions" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Name.
	"name" TEXT NOT NULL,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Description.
	"description" TEXT,
	-- Identifier of the commission president.
	"president_id" UUID NOT NULL,
	-- Record creation timestamp.
	"creation_date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "commissions"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "commissions"."name" IS 'Name.';
COMMENT ON COLUMN "commissions"."code" IS 'Unique code.';
COMMENT ON COLUMN "commissions"."description" IS 'Description.';
COMMENT ON COLUMN "commissions"."president_id" IS 'Identifier of the commission president.';
COMMENT ON COLUMN "commissions"."creation_date" IS 'Record creation timestamp.';

CREATE TABLE IF NOT EXISTS "commissions_members" (
	-- Identifier of the associated commission.
	"commission_id" INTEGER NOT NULL,
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Date when the member joined.
	"joined_at" DATE NOT NULL,
	PRIMARY KEY("commission_id", "person_id")
);

COMMENT ON COLUMN "commissions_members"."commission_id" IS 'Identifier of the associated commission.';
COMMENT ON COLUMN "commissions_members"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "commissions_members"."joined_at" IS 'Date when the member joined.';

CREATE TABLE IF NOT EXISTS "payments" (
	-- Unique identifier for this record.
	"id" UUID NOT NULL  DEFAULT gen_random_uuid(),
	-- Identifier of the associated person.
	"person_id" UUID NOT NULL,
	-- Identifier of the associated license.
	"license_id" UUID NOT NULL,
	-- Payment amount.
	"amount" NUMERIC(8,2) NOT NULL,
	-- Payment currency.
	"currency" CHAR(3) NOT NULL CHECK ("currency" ~ '^[A-Z]{3}$'),
	-- Payment method.
	"payment_method" payments_method NOT NULL,
	-- Payment status.
	"payment_status" payments_status NOT NULL,
	-- Payment date.
	"payment_date" TIMESTAMPTZ NOT NULL,
	-- Transaction reference.
	"transaction_reference" TEXT NOT NULL UNIQUE,
	-- Identifier of the invoice document.
	"invoice_document" UUID,
	-- Additional notes.
	"notes" TEXT,
	-- Creation timestamp.
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Last update timestamp.
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id"),

	CONSTRAINT check_amount_positive CHECK ("amount" > 0)
);

COMMENT ON COLUMN "payments"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "payments"."person_id" IS 'Identifier of the associated person.';
COMMENT ON COLUMN "payments"."license_id" IS 'Identifier of the associated license.';
COMMENT ON COLUMN "payments"."amount" IS 'Payment amount.';
COMMENT ON COLUMN "payments"."payment_method" IS 'Payment method.';
COMMENT ON COLUMN "payments"."payment_status" IS 'Payment status.';
COMMENT ON COLUMN "payments"."payment_date" IS 'Payment date.';
COMMENT ON COLUMN "payments"."transaction_reference" IS 'Transaction reference.';
COMMENT ON COLUMN "payments"."invoice_document" IS 'Identifier of the invoice document.';
COMMENT ON COLUMN "payments"."notes" IS 'Additional notes.';
COMMENT ON COLUMN "payments"."created_at" IS 'Creation timestamp.';
COMMENT ON COLUMN "payments"."updated_at" IS 'Last update timestamp.';

CREATE TABLE IF NOT EXISTS "payments_history" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Identifier of the associated payment.
	"payment_id" UUID NOT NULL,
	-- Previous status.
	"previous_status" payments_method NOT NULL,
	-- New status.
	"new_status" payments_status NOT NULL,
	-- Identifier of the user who made the change.
	"changed_by" UUID,
	-- Change timestamp.
	"changed_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Reason for the change.
	"reason" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "payments_history"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "payments_history"."payment_id" IS 'Identifier of the associated payment.';
COMMENT ON COLUMN "payments_history"."previous_status" IS 'Previous status.';
COMMENT ON COLUMN "payments_history"."new_status" IS 'New status.';
COMMENT ON COLUMN "payments_history"."changed_by" IS 'Identifier of the user who made the change.';
COMMENT ON COLUMN "payments_history"."changed_at" IS 'Change timestamp.';
COMMENT ON COLUMN "payments_history"."reason" IS 'Reason for the change.';

CREATE TABLE IF NOT EXISTS "users_status" (
	-- Unique identifier for this record.
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Unique code.
	"code" TEXT NOT NULL UNIQUE,
	-- Display label.
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id"),
	CONSTRAINT "users_status_unique_0" UNIQUE ("code", "label")
);

COMMENT ON COLUMN "users_status"."id" IS 'Unique identifier for this record.';
COMMENT ON COLUMN "users_status"."code" IS 'Unique code.';
COMMENT ON COLUMN "users_status"."label" IS 'Display label.';

CREATE TABLE IF NOT EXISTS "logs" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    user_id UUID NULL,

    action VARCHAR(30) NOT NULL,

    schema_name VARCHAR(63) NOT NULL,

    table_name VARCHAR(63) NOT NULL,

	metadata JSONB NULL,

	ip_address INET NULL, 

    user_agent TEXT NULL,

    CONSTRAINT logs_user_fk
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE SET NULL,

    CONSTRAINT logs_action_check
        CHECK (
    action IN (
        'INSERT',
        'UPDATE',
        'DELETE',
        'LOGIN',
        'LOGOUT',
        'READ',
        'EXPORT'
    )
)
);

ALTER TABLE "competitions"
ADD FOREIGN KEY("season_id") REFERENCES "seasons"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "licenses"
ADD FOREIGN KEY("season_id") REFERENCES "seasons"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "practice_sites"
ADD FOREIGN KEY("municipality_id") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "municipalities"
ADD FOREIGN KEY("development_status") REFERENCES "development_status"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "competitions"
ADD FOREIGN KEY("location_id") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competitions"
ADD FOREIGN KEY("practice_site_id") REFERENCES "practice_sites"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competitions"
ADD FOREIGN KEY("organizer_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competitions"
ADD FOREIGN KEY("format_id") REFERENCES "competition_formats"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "games"
ADD FOREIGN KEY("competition_id") REFERENCES "competitions"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "games"
ADD FOREIGN KEY("format_id") REFERENCES "game_format"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "teams"
ADD FOREIGN KEY("competition_id") REFERENCES "competitions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "team_members"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "team_members"
ADD FOREIGN KEY("team_id") REFERENCES "teams"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "game_side"
ADD FOREIGN KEY("game_id") REFERENCES "games"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "game_side_result"
ADD FOREIGN KEY("game_side_id") REFERENCES "game_side"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("license_id") REFERENCES "licenses"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "game_participant"
ADD FOREIGN KEY("game_side_id") REFERENCES "game_side"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "game_participant"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "users"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "licenses"
ADD FOREIGN KEY("license_type") REFERENCES "license_types"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "slots"
ADD FOREIGN KEY("site_id") REFERENCES "practice_sites"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "slots"
ADD FOREIGN KEY("season_id") REFERENCES "seasons"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "referents"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "referents"
ADD FOREIGN KEY("site_id") REFERENCES "practice_sites"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "sessions"
ADD FOREIGN KEY("slot_id") REFERENCES "slots"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "sessions"
ADD FOREIGN KEY("referent_id") REFERENCES "referents"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "session_participants"
ADD FOREIGN KEY("session_id") REFERENCES "sessions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "session_participants"
ADD FOREIGN KEY("license_id") REFERENCES "licenses"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "session_participants"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "volunteers"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "volunteers"
ADD FOREIGN KEY("manager_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "volunteers"
ADD FOREIGN KEY("location") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "contacts"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "contacts"
ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "contacts"
ADD FOREIGN KEY("responsible_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "users_roles"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "prospects"
ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "organizations_contact"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "person_roles"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "persons"
ADD FOREIGN KEY("municipality_id") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "persons"
ADD FOREIGN KEY("status") REFERENCES "person_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "person_roles"
ADD FOREIGN KEY("role_id") REFERENCES "roles"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("competition_id") REFERENCES "competitions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents"
ADD FOREIGN KEY("document_type_id") REFERENCES "document_types"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "licenses"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "municipalities"
ADD FOREIGN KEY("departement_id") REFERENCES "departments"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "departments"
ADD FOREIGN KEY("region_id") REFERENCES "regions"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "regions"
ADD FOREIGN KEY("country_id") REFERENCES "countries"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "referents"
ADD FOREIGN KEY("status") REFERENCES "referent_status"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "organizations"
ADD FOREIGN KEY("organization_type_id") REFERENCES "organization_types"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "users_roles"
ADD FOREIGN KEY("role_id") REFERENCES "access_roles"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "prospects"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "organizations"
ADD FOREIGN KEY("municipality_id") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "organizations_contact"
ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "competitions"
ADD FOREIGN KEY("rules_document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "licenses"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "consents"
ADD FOREIGN KEY("consent_type_id") REFERENCES "consents_type"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "consents"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "documents"
ADD FOREIGN KEY("uploaded_by") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "competitions"
ADD FOREIGN KEY("status") REFERENCES "competition_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "documents_persons"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_practices_sites"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_commissions"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_projects"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_competitions"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_licenses"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_organizations"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_organizations"
ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_competitions"
ADD FOREIGN KEY("competition_id") REFERENCES "competitions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_licenses"
ADD FOREIGN KEY("license_id") REFERENCES "licenses"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_persons"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "projects"
ADD FOREIGN KEY("status") REFERENCES "projects_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "projects_members"
ADD FOREIGN KEY("project_id") REFERENCES "projects"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "projects_members"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "projects_members"
ADD FOREIGN KEY("project_role") REFERENCES "projects_members_role"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "documents_projects"
ADD FOREIGN KEY("project_id") REFERENCES "projects"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "commissions"
ADD FOREIGN KEY("president_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "commissions_members"
ADD FOREIGN KEY("commission_id") REFERENCES "commissions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "commissions_members"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_commissions"
ADD FOREIGN KEY("commission_id") REFERENCES "commissions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("category") REFERENCES "competition_participant_category"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("status") REFERENCES "competition_participant_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "payments_history"
ADD FOREIGN KEY("payment_id") REFERENCES "payments"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "payments"
ADD FOREIGN KEY("invoice_document") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "payments"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "payments"
ADD FOREIGN KEY("license_id") REFERENCES "licenses"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "documents_practices_sites"
ADD FOREIGN KEY("practice_site_id") REFERENCES "practice_sites"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "sessions"
ADD FOREIGN KEY("coach_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "users"
ADD FOREIGN KEY("statut") REFERENCES "users_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "payments_history"
ADD FOREIGN KEY("changed_by") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "equipments" ADD FOREIGN KEY("category_id") REFERENCES "equipment_categories"("id") 
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "equipments" ADD FOREIGN KEY("status_id") REFERENCES "equipment_status"("id") 
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "equipments" ADD FOREIGN KEY("practice_site_id") REFERENCES "practice_sites"("id") 
ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "licenses"
ADD CONSTRAINT uq_licenses_id_person
UNIQUE (id, person_id);

ALTER TABLE "competition_participant"
ADD CONSTRAINT fk_competition_participant_license_person
FOREIGN KEY (license_id, person_id)
REFERENCES "licenses" (id, person_id);

ALTER TABLE "session_participants"
ADD CONSTRAINT fk_session_participant_license_person
FOREIGN KEY (license_id, person_id)
REFERENCES "licenses" (id, person_id);

ALTER TABLE "game_side"
ADD FOREIGN KEY ("person_id")
REFERENCES "persons"("ff2b_id")
ON DELETE RESTRICT;

ALTER TABLE "game_side"
ADD FOREIGN KEY ("team_id")
REFERENCES "teams"("id")
ON DELETE RESTRICT;

ALTER TABLE "game_participant"
ADD CONSTRAINT game_participant_side_person_unique
UNIQUE ("game_side_id", "person_id");

-- Validates score symmetry, completed-game completeness, and competition/team consistency.
CREATE OR REPLACE FUNCTION validate_game_integrity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_game_id INTEGER;
    v_status GAME_STATUS;
    v_side_count INTEGER;
    v_result_count INTEGER;
BEGIN
    IF TG_TABLE_NAME = 'games' THEN
        v_game_id := COALESCE(NEW.id, OLD.id);
    ELSIF TG_TABLE_NAME = 'game_side' THEN
        v_game_id := COALESCE(NEW.game_id, OLD.game_id);
    ELSIF TG_OP = 'DELETE' AND TG_TABLE_NAME = 'game_side_result' THEN
        SELECT gs.game_id
        INTO v_game_id
        FROM game_side gs
        WHERE gs.id = OLD.game_side_id;
    ELSE
        SELECT gs.game_id
        INTO v_game_id
        FROM game_side_result gsr
        JOIN game_side gs ON gs.id = gsr.game_side_id
        WHERE gsr.game_side_id = COALESCE(NEW.game_side_id, OLD.game_side_id)
        LIMIT 1;
    END IF;

    SELECT g.status
    INTO v_status
    FROM games g
    WHERE g.id = v_game_id;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM game_side gs
        JOIN teams t ON t.id = gs.team_id
        JOIN games g ON g.id = gs.game_id
        WHERE gs.game_id = v_game_id
          AND g.competition_id IS NOT NULL
          AND t.competition_id <> g.competition_id
    ) THEN
        RAISE EXCEPTION
            'A team used in game % must belong to the same competition as the game',
            v_game_id;
    END IF;

    IF (
        SELECT COUNT(*)
        FROM game_side_result r
        JOIN game_side gs ON gs.id = r.game_side_id
        WHERE gs.game_id = v_game_id
    ) = 2
    AND EXISTS (
        SELECT 1
        FROM game_side gs1
        JOIN game_side_result r1 ON r1.game_side_id = gs1.id
        JOIN game_side gs2
          ON gs2.game_id = gs1.game_id
         AND gs2.side_number <> gs1.side_number
        JOIN game_side_result r2 ON r2.game_side_id = gs2.id
        WHERE gs1.game_id = v_game_id
          AND (
              r1.nieshs_scored <> r2.nieshs_conceded
              OR r1.nieshs_conceded <> r2.nieshs_scored
          )
    ) THEN
        RAISE EXCEPTION
            'Scores for the two sides of game % must be reciprocal',
            v_game_id;
    END IF;

    IF v_status = 'completed' THEN
        SELECT COUNT(*) INTO v_side_count
        FROM game_side
        WHERE game_id = v_game_id;

        SELECT COUNT(*) INTO v_result_count
        FROM game_side_result r
        JOIN game_side gs ON gs.id = r.game_side_id
        WHERE gs.game_id = v_game_id;

        IF v_side_count <> 2 OR v_result_count <> 2 THEN
            RAISE EXCEPTION
                'Completed game % must have exactly two sides and two results',
                v_game_id;
        END IF;

        IF EXISTS (
            SELECT 1
            FROM game_side gs
            WHERE gs.game_id = v_game_id
              AND (
                  (
                      gs.person_id IS NOT NULL
                      AND NOT EXISTS (
                          SELECT 1
                          FROM game_participant gp
                          WHERE gp.game_side_id = gs.id
                            AND gp.person_id = gs.person_id
                      )
                  )
                  OR
                  (
                      gs.team_id IS NOT NULL
                      AND NOT EXISTS (
                          SELECT 1
                          FROM game_participant gp
                          WHERE gp.game_side_id = gs.id
                      )
                  )
              )
        ) THEN
            RAISE EXCEPTION
                'Every side of completed game % must have valid participants',
                v_game_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

-- Validates participant uniqueness, individual-side identity, and team membership.
CREATE OR REPLACE FUNCTION validate_game_participant()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_game_id INTEGER;
    v_side_person UUID;
    v_team_id INTEGER;
BEGIN
    IF TG_TABLE_NAME = 'game_participant' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN NULL;
        END IF;

        SELECT gs.game_id, gs.person_id, gs.team_id
        INTO v_game_id, v_side_person, v_team_id
        FROM game_side gs
        WHERE gs.id = NEW.game_side_id;

        IF v_team_id IS NULL AND v_side_person IS DISTINCT FROM NEW.person_id THEN
            RAISE EXCEPTION
                'An individual game side can only contain its declared person';
        END IF;

        IF v_team_id IS NOT NULL
           AND NOT EXISTS (
               SELECT 1
               FROM team_members tm
               WHERE tm.team_id = v_team_id
                 AND tm.person_id = NEW.person_id
           ) THEN
            RAISE EXCEPTION
                'Person % is not a member of team %',
                NEW.person_id, v_team_id;
        END IF;

        IF EXISTS (
            SELECT 1
            FROM game_participant gp
            JOIN game_side other_side ON other_side.id = gp.game_side_id
            WHERE other_side.game_id = v_game_id
              AND gp.person_id = NEW.person_id
              AND gp.id <> NEW.id
        ) THEN
            RAISE EXCEPTION
                'Person % cannot participate on both sides of game %',
                NEW.person_id, v_game_id;
        END IF;
    ELSE
        SELECT gs.game_id, gs.person_id, gs.team_id
        INTO v_game_id, v_side_person, v_team_id
        FROM game_side gs
        WHERE gs.id = COALESCE(NEW.id, OLD.id);

        IF v_side_person IS NOT NULL
           AND EXISTS (
               SELECT 1
               FROM game_participant gp
               WHERE gp.game_side_id = COALESCE(NEW.id, OLD.id)
                 AND gp.person_id IS DISTINCT FROM v_side_person
           ) THEN
            RAISE EXCEPTION
                'An individual game side cannot contain another person';
        END IF;

        IF v_team_id IS NOT NULL
           AND EXISTS (
               SELECT 1
               FROM game_participant gp
               WHERE gp.game_side_id = COALESCE(NEW.id, OLD.id)
                 AND NOT EXISTS (
                     SELECT 1
                     FROM team_members tm
                     WHERE tm.team_id = v_team_id
                       AND tm.person_id = gp.person_id
                 )
           ) THEN
            RAISE EXCEPTION
                'Every participant on a team side must belong to that team';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM game_participant gp
            JOIN game_side other_side ON other_side.id = gp.game_side_id
            WHERE gp.game_side_id = COALESCE(NEW.id, OLD.id)
              AND EXISTS (
                  SELECT 1
                  FROM game_participant other_gp
                  JOIN game_side other_game_side
                    ON other_game_side.id = other_gp.game_side_id
                  WHERE other_game_side.game_id = v_game_id
                    AND other_gp.person_id = gp.person_id
                    AND other_gp.game_side_id <> gp.game_side_id
              )
        ) THEN
            RAISE EXCEPTION
                'A person cannot participate on both sides of game %',
                v_game_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

-- Prevents removing or changing a team member while that person is used in a game.
CREATE OR REPLACE FUNCTION validate_team_membership_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM game_participant gp
        JOIN game_side gs ON gs.id = gp.game_side_id
        WHERE (gs.team_id = OLD.team_id OR gs.team_id = NEW.team_id)
          AND gp.person_id = COALESCE(OLD.person_id, NEW.person_id)
          AND NOT EXISTS (
              SELECT 1
              FROM team_members tm
              WHERE tm.team_id = gs.team_id
                AND tm.person_id = gp.person_id
          )
    ) THEN
        RAISE EXCEPTION
            'A team member cannot be removed while participating in a game';
    END IF;

    RETURN NULL;
END;
$$;

-- Prevents changing a team's competition while it is used in another competition.
CREATE OR REPLACE FUNCTION validate_team_competition_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM game_side gs
        JOIN games g ON g.id = gs.game_id
        WHERE gs.team_id = COALESCE(NEW.id, OLD.id)
          AND g.competition_id IS NOT NULL
          AND g.competition_id <> COALESCE(NEW.competition_id, OLD.competition_id)
    ) THEN
        RAISE EXCEPTION
            'A team competition cannot be changed while the team is used in a game';
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER game_integrity_on_games
AFTER INSERT OR UPDATE OR DELETE ON games
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_game_integrity();

CREATE CONSTRAINT TRIGGER game_integrity_on_sides
AFTER INSERT OR UPDATE OR DELETE ON game_side
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_game_integrity();

CREATE CONSTRAINT TRIGGER game_integrity_on_results
AFTER INSERT OR UPDATE OR DELETE ON game_side_result
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_game_integrity();

CREATE CONSTRAINT TRIGGER game_participant_integrity
AFTER INSERT OR UPDATE OR DELETE ON game_participant
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_game_participant();

CREATE CONSTRAINT TRIGGER game_side_participant_integrity
AFTER INSERT OR UPDATE OR DELETE ON game_side
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_game_participant();

CREATE CONSTRAINT TRIGGER team_membership_game_integrity
AFTER UPDATE OR DELETE ON team_members
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_team_membership_change();

CREATE CONSTRAINT TRIGGER team_competition_game_integrity
AFTER UPDATE ON teams
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_team_competition_change();

-- Table descriptions.
COMMENT ON TABLE "persons" IS 'Stores persons records.';
COMMENT ON TABLE "person_status" IS 'Stores person status records.';
COMMENT ON TABLE "person_roles" IS 'Stores person role records.';
COMMENT ON TABLE "roles" IS 'Stores roles records.';
COMMENT ON TABLE "licenses" IS 'Stores licenses records.';
COMMENT ON TABLE "license_types" IS 'Stores license type records.';
COMMENT ON TABLE "seasons" IS 'Stores seasons records.';
COMMENT ON TABLE "municipalities" IS 'Stores municipalities records.';
COMMENT ON TABLE "departments" IS 'Stores departments records.';
COMMENT ON TABLE "regions" IS 'Stores regions records.';
COMMENT ON TABLE "countries" IS 'Stores countries records.';
COMMENT ON TABLE "practice_sites" IS 'Stores practice sites records.';
COMMENT ON TABLE "equipments" IS 'Stores equipments records.';
COMMENT ON TABLE "equipment_categories" IS 'Stores equipment category records.';
COMMENT ON TABLE "equipment_status" IS 'Stores equipment status records.';
COMMENT ON TABLE "slots" IS 'Stores slots records.';
COMMENT ON TABLE "sessions" IS 'Stores sessions records.';
COMMENT ON TABLE "session_participants" IS 'Stores session participants records.';
COMMENT ON TABLE "competitions" IS 'Stores competitions records.';
COMMENT ON TABLE "competition_formats" IS 'Stores competition format records.';
COMMENT ON TABLE "competition_status" IS 'Stores competition status records.';
COMMENT ON TABLE "competition_participant" IS 'Stores competition participant records.';
COMMENT ON TABLE "competition_participant_status" IS 'Stores competition participant status records.';
COMMENT ON TABLE "competition_participant_category" IS 'Stores competition participant category records.';
COMMENT ON TABLE "games" IS 'Stores games records.';
COMMENT ON TABLE "game_format" IS 'Stores game format records.';
COMMENT ON TABLE "game_participant" IS 'Stores game participant records.';
COMMENT ON TABLE "game_side" IS 'Stores game side records.';
COMMENT ON TABLE "game_side_result" IS 'Stores game side result records.';
COMMENT ON TABLE "teams" IS 'Stores team records.';
COMMENT ON TABLE "team_members" IS 'Stores team members records.';
COMMENT ON TABLE "referents" IS 'Stores referents records.';
COMMENT ON TABLE "referent_status" IS 'Stores referent status records.';
COMMENT ON TABLE "volunteers" IS 'Stores volunteers records.';
COMMENT ON TABLE "organizations" IS 'Stores organizations records.';
COMMENT ON TABLE "organization_types" IS 'Stores organizations type records.';
COMMENT ON TABLE "organizations_contact" IS 'Stores organizations contact records.';
COMMENT ON TABLE "prospects" IS 'Stores prospects records.';
COMMENT ON TABLE "contacts" IS 'Stores contacts records.';
COMMENT ON TABLE "users" IS 'Stores users records.';
COMMENT ON TABLE "access_roles" IS 'Stores access roles records.';
COMMENT ON TABLE "users_roles" IS 'Stores users roles records.';
COMMENT ON TABLE "consents" IS 'Stores consents records.';
COMMENT ON TABLE "consents_type" IS 'Stores consents type records.';
COMMENT ON TABLE "documents" IS 'Stores documents records.';
COMMENT ON TABLE "document_types" IS 'Stores document type records.';
COMMENT ON TABLE "documents_persons" IS 'Stores documents persons records.';
COMMENT ON TABLE "documents_competitions" IS 'Stores documents competitions records.';
COMMENT ON TABLE "documents_licenses" IS 'Stores documents licenses records.';
COMMENT ON TABLE "documents_projects" IS 'Stores documents projects records.';
COMMENT ON TABLE "documents_commissions" IS 'Stores documents commissions records.';
COMMENT ON TABLE "documents_organizations" IS 'Stores documents organizations records.';
COMMENT ON TABLE "documents_practices_sites" IS 'Stores documents practices sites records.';
COMMENT ON TABLE "projects" IS 'Stores projects records.';
COMMENT ON TABLE "projects_members" IS 'Stores projects members records.';
COMMENT ON TABLE "projects_members_role" IS 'Stores project members role records.';
COMMENT ON TABLE "projects_status" IS 'Stores projects status records.';
COMMENT ON TABLE "commissions" IS 'Stores commissions records.';
COMMENT ON TABLE "commissions_members" IS 'Stores commissions members records.';
COMMENT ON TABLE "payments" IS 'Stores payments records.';
COMMENT ON TABLE "payments_history" IS 'Stores payments history records.';
COMMENT ON TABLE "users_status" IS 'Stores users status records.';
COMMENT ON TABLE "logs" IS 'Stores logs records.';
COMMENT ON TABLE "development_status" IS 'Stores the development status of a record';

-- Reverse-lookup indexes for junction tables and foreign keys.

CREATE INDEX IF NOT EXISTS idx_logs_table_changed_at
    ON "logs" ("table_name", "changed_at" DESC);

CREATE INDEX IF NOT EXISTS idx_logs_user_changed_at
    ON "logs" ("user_id", "changed_at" DESC);

CREATE INDEX IF NOT EXISTS idx_logs_action
    ON "logs" ("action");

CREATE INDEX IF NOT EXISTS idx_persons_municipality_id
    ON persons (municipality_id);

CREATE INDEX IF NOT EXISTS idx_persons_last_name
    ON persons (last_name);

CREATE INDEX IF NOT EXISTS idx_persons_birthdate
    ON persons (birthdate);


CREATE INDEX IF NOT EXISTS idx_person_roles_person_id
    ON person_roles (person_id);

CREATE INDEX IF NOT EXISTS idx_licenses_license_type
    ON licenses (license_type);


CREATE INDEX IF NOT EXISTS idx_licenses_season
    ON licenses (season_id);

CREATE INDEX IF NOT EXISTS idx_licenses_document_id
    ON licenses (document_id);

CREATE INDEX IF NOT EXISTS idx_licenses_license_status
    ON licenses (license_status);

CREATE INDEX IF NOT EXISTS idx_licenses_end_date
    ON licenses (end_date);

CREATE INDEX IF NOT EXISTS idx_licenses_request_date
    ON licenses (request_date);

CREATE INDEX IF NOT EXISTS idx_licenses_person_season
    ON licenses (person_id, season_id);




CREATE INDEX IF NOT EXISTS idx_municipalities_department_id
    ON municipalities (departement_id);

CREATE INDEX IF NOT EXISTS idx_municipalities_name
    ON municipalities (name);

CREATE INDEX IF NOT EXISTS idx_municipalities_insee_code
    ON municipalities (insee_code);


CREATE INDEX IF NOT EXISTS idx_departments_region_id
    ON departments (region_id);

CREATE INDEX IF NOT EXISTS idx_departments_code
    ON departments (code);


CREATE INDEX IF NOT EXISTS idx_regions_country_id
    ON regions (country_id);

CREATE INDEX IF NOT EXISTS idx_regions_code
    ON regions (code);


CREATE INDEX IF NOT EXISTS idx_countries_code
    ON countries (code);


CREATE INDEX IF NOT EXISTS idx_practice_site_municipality_id
    ON practice_sites (municipality_id);

CREATE INDEX IF NOT EXISTS idx_practice_site_name
    ON practice_sites (name);



CREATE INDEX IF NOT EXISTS idx_slots_season_id
    ON slots (season_id);

CREATE INDEX IF NOT EXISTS idx_slots_site_season
    ON slots (site_id, season_id);

CREATE INDEX IF NOT EXISTS idx_slots_day_of_week
    ON slots (day_of_week);



CREATE INDEX IF NOT EXISTS idx_sessions_referent_id
    ON sessions (referent_id);

CREATE INDEX IF NOT EXISTS idx_sessions_coach_id
    ON sessions (coach_id);

CREATE INDEX IF NOT EXISTS idx_sessions_start_time
    ON sessions (start_at);

CREATE INDEX IF NOT EXISTS idx_sessions_status
    ON sessions (status);

CREATE INDEX IF NOT EXISTS idx_sessions_slot_start_time
    ON sessions (slot_id, start_at);


CREATE INDEX IF NOT EXISTS idx_session_participants_session_id
    ON session_participants (session_id);

CREATE INDEX IF NOT EXISTS idx_session_participants_license_id
    ON session_participants (license_id);


CREATE INDEX IF NOT EXISTS idx_competitions_season_id
    ON competitions (season_id);

CREATE INDEX IF NOT EXISTS idx_competitions_location_id
    ON competitions (location_id);

CREATE INDEX IF NOT EXISTS idx_competitions_practice_site_id
    ON competitions (practice_site_id);

CREATE INDEX IF NOT EXISTS idx_competitions_organizer_id
    ON competitions (organizer_id);

CREATE INDEX IF NOT EXISTS idx_competitions_format_id
    ON competitions (format_id);

CREATE INDEX IF NOT EXISTS idx_competitions_status
    ON competitions (status);

CREATE INDEX IF NOT EXISTS idx_competitions_rules_document_id
    ON competitions (rules_document_id);

CREATE INDEX IF NOT EXISTS idx_competitions_date
    ON competitions (date);

CREATE INDEX IF NOT EXISTS idx_competitions_season_date
    ON competitions (season_id, date);



CREATE INDEX IF NOT EXISTS idx_competition_participant_person_id
    ON competition_participant (person_id);

CREATE INDEX IF NOT EXISTS idx_competition_participant_status
    ON competition_participant (status);

CREATE INDEX IF NOT EXISTS idx_competition_participant_category
    ON competition_participant (category);

CREATE INDEX IF NOT EXISTS idx_competition_participant_license_id
    ON competition_participant (license_id);

CREATE INDEX IF NOT EXISTS idx_competition_participant_competition_person
    ON competition_participant (competition_id, person_id);


CREATE INDEX IF NOT EXISTS idx_games_competition_id
    ON games (competition_id);

CREATE INDEX IF NOT EXISTS idx_games_format_id
    ON games (format_id);

CREATE INDEX IF NOT EXISTS idx_games_date
    ON games (date);

CREATE INDEX IF NOT EXISTS idx_games_status
    ON games (status);

CREATE INDEX IF NOT EXISTS idx_games_competition_date
    ON games (competition_id, date);


CREATE INDEX IF NOT EXISTS idx_game_participant_game_side_id
    ON game_participant (game_side_id);

CREATE INDEX IF NOT EXISTS idx_game_participant_person_id
    ON game_participant (person_id);


CREATE INDEX IF NOT EXISTS idx_team_members_person_id
    ON team_members (person_id);


CREATE INDEX IF NOT EXISTS idx_referents_person_id
    ON referents (person_id);

CREATE INDEX IF NOT EXISTS idx_referents_site_id
    ON referents (site_id);

CREATE INDEX IF NOT EXISTS idx_referents_status
    ON referents (status);

CREATE INDEX IF NOT EXISTS idx_referents_site_start_date
    ON referents (site_id, start_date);


CREATE INDEX IF NOT EXISTS idx_volunteers_person_id
    ON volunteers (person_id);

CREATE INDEX IF NOT EXISTS idx_volunteers_manager_id
    ON volunteers (manager_id);

CREATE INDEX IF NOT EXISTS idx_volunteers_location
    ON volunteers (location);

CREATE INDEX IF NOT EXISTS idx_volunteers_start_date
    ON volunteers (start_date);

CREATE INDEX IF NOT EXISTS idx_volunteers_end_date
    ON volunteers (end_date);


CREATE INDEX IF NOT EXISTS idx_organizations_organization_type_id
    ON organizations (organization_type_id);

CREATE INDEX IF NOT EXISTS idx_organizations_municipality_id
    ON organizations (municipality_id);

CREATE INDEX IF NOT EXISTS idx_organizations_name
    ON organizations (name);


CREATE INDEX IF NOT EXISTS idx_organizations_contact_organization_id
    ON organizations_contact (organization_id);

CREATE INDEX IF NOT EXISTS idx_organizations_contact_person_id
    ON organizations_contact (person_id);


CREATE INDEX IF NOT EXISTS idx_prospects_person_id
    ON prospects (person_id);

CREATE INDEX IF NOT EXISTS idx_prospects_organization_id
    ON prospects (organization_id);

CREATE INDEX IF NOT EXISTS idx_prospects_type
    ON prospects (type);

CREATE INDEX IF NOT EXISTS idx_prospects_status
    ON prospects (status);


CREATE INDEX IF NOT EXISTS idx_contacts_person_id
    ON contacts (person_id);

CREATE INDEX IF NOT EXISTS idx_contacts_organization_id
    ON contacts (organization_id);


CREATE INDEX IF NOT EXISTS idx_contacts_date
    ON contacts (contact_at);

CREATE INDEX IF NOT EXISTS idx_contacts_responsible_date
    ON contacts (responsible_id, contact_at);


CREATE INDEX IF NOT EXISTS idx_users_email
    ON users (email);

CREATE INDEX IF NOT EXISTS idx_users_statut
    ON users (statut);


CREATE INDEX IF NOT EXISTS idx_users_roles_user_id
    ON users_roles (user_id);


CREATE INDEX IF NOT EXISTS idx_consents_person_id
    ON consents (person_id);

CREATE INDEX IF NOT EXISTS idx_consents_consent_type_id
    ON consents (consent_type_id);

CREATE INDEX IF NOT EXISTS idx_consents_person_type
    ON consents (person_id, consent_type_id);

CREATE INDEX IF NOT EXISTS idx_consents_given_at
    ON consents (given_at);


CREATE INDEX IF NOT EXISTS idx_documents_document_type_id
    ON documents (document_type_id);

CREATE INDEX IF NOT EXISTS idx_documents_uploaded_by
    ON documents (uploaded_by);

CREATE INDEX IF NOT EXISTS idx_documents_hash
    ON documents (hash);

CREATE INDEX IF NOT EXISTS idx_documents_creation_date
    ON documents (creation_date);

CREATE INDEX IF NOT EXISTS idx_documents_expires_at
    ON documents (expires_at);


CREATE INDEX IF NOT EXISTS idx_documents_persons_person_id
    ON documents_persons (person_id);


CREATE INDEX IF NOT EXISTS idx_documents_competitions_competition_id
    ON documents_competitions (competition_id);


CREATE INDEX IF NOT EXISTS idx_documents_licenses_license_id
    ON documents_licenses (license_id);


CREATE INDEX IF NOT EXISTS idx_documents_projects_project_id
    ON documents_projects (project_id);


CREATE INDEX IF NOT EXISTS idx_documents_commissions_commission_id
    ON documents_commissions (commission_id);


CREATE INDEX IF NOT EXISTS idx_documents_organizations_organization_id
    ON documents_organizations (organization_id);


CREATE INDEX IF NOT EXISTS idx_documents_practices_sites_practice_site_id
    ON documents_practices_sites (practice_site_id);


CREATE INDEX IF NOT EXISTS idx_projects_status
    ON projects (status);

CREATE INDEX IF NOT EXISTS idx_projects_start_date
    ON projects (start_date);

CREATE INDEX IF NOT EXISTS idx_projects_end_date
    ON projects (end_date);

CREATE INDEX IF NOT EXISTS idx_projects_status_start_date
    ON projects (status, start_date);


CREATE INDEX IF NOT EXISTS idx_projects_members_person_id
    ON projects_members (person_id);

CREATE INDEX IF NOT EXISTS idx_projects_members_project_role
    ON projects_members (project_role);


CREATE INDEX IF NOT EXISTS idx_commissions_president_id
    ON commissions (president_id);

CREATE INDEX IF NOT EXISTS idx_commissions_name
    ON commissions (name);


CREATE INDEX IF NOT EXISTS idx_commissions_members_person_id
    ON commissions_members (person_id);




CREATE INDEX IF NOT EXISTS idx_payments_payment_status
    ON payments (payment_status);

CREATE INDEX IF NOT EXISTS idx_payments_payment_date
    ON payments (payment_date);

CREATE INDEX IF NOT EXISTS idx_payments_person_date
    ON payments (person_id, payment_date);

CREATE INDEX IF NOT EXISTS idx_payments_license_date
    ON payments (license_id, payment_date);


CREATE INDEX IF NOT EXISTS idx_payments_history_payment_id
    ON payments_history (payment_id);

CREATE INDEX IF NOT EXISTS idx_payments_history_changed_by
    ON payments_history (changed_by);

CREATE INDEX IF NOT EXISTS idx_payments_history_changed_at
    ON payments_history (changed_at);

CREATE INDEX IF NOT EXISTS idx_payments_history_payment_changed_at
    ON payments_history (payment_id, changed_at);

CREATE INDEX IF NOT EXISTS "idx_equipment_site_id" ON "equipments" ("practice_site_id");
CREATE INDEX IF NOT EXISTS "idx_equipment_category_id" ON "equipments" ("category_id");
CREATE INDEX IF NOT EXISTS "idx_equipment_status_id" ON "equipments" ("status_id");

-- Schema documentation.
CREATE INDEX IF NOT EXISTS idx_person_roles_role_id ON person_roles (role_id);
CREATE INDEX IF NOT EXISTS idx_session_participants_person_id ON session_participants (person_id);
CREATE INDEX IF NOT EXISTS idx_team_members_team_id ON team_members (team_id);
CREATE INDEX IF NOT EXISTS idx_users_roles_role_id ON users_roles (role_id);
CREATE INDEX IF NOT EXISTS idx_documents_persons_document_id ON documents_persons (document_id);
CREATE INDEX IF NOT EXISTS idx_documents_competitions_document_id ON documents_competitions (document_id);
CREATE INDEX IF NOT EXISTS idx_documents_licenses_document_id ON documents_licenses (document_id);
CREATE INDEX IF NOT EXISTS idx_documents_projects_document_id ON documents_projects (document_id);
CREATE INDEX IF NOT EXISTS idx_documents_commissions_document_id ON documents_commissions (document_id);
CREATE INDEX IF NOT EXISTS idx_documents_organizations_document_id ON documents_organizations (document_id);
CREATE INDEX IF NOT EXISTS idx_documents_practices_sites_document_id ON documents_practices_sites (document_id);
CREATE INDEX IF NOT EXISTS idx_projects_members_project_id ON projects_members (project_id);
CREATE INDEX IF NOT EXISTS idx_commissions_members_commission_id ON commissions_members (commission_id);
