CREATE TYPE "licence_status" AS ENUM (
	'brouillon',
	'demandée',
	'en attente',
	'validée',
	'suspendue',
	'expirée',
	'annulée'
);

CREATE TYPE "contact_origin" AS ENUM (
	'internet',
	'IA',
	'téléphone',
	'email'
);

CREATE TYPE "seance_status" AS ENUM (
	'annulé',
	'reporté',
	'terminé',
	'en cours',
	'planifié'
);

CREATE TYPE "payments_method" AS ENUM (
	'carte_bancaire',
	'virement',
	'cheque',
	'especes',
	'pass_sport',
	'autre'
);

CREATE TYPE "payments_status" AS ENUM (
	'en_attente',
	'valide',
	'echoue',
	'rembourse',
	'annule'
);

CREATE TABLE IF NOT EXISTS "persons" (
	-- Identifiant unique de la personne au sein de l'organisation
	"ff2b_id" UUID NOT NULL DEFAULT gen_random_uuid(),
	-- Prénom de la personne
	"first_name" TEXT NOT NULL,
	-- Nom de famille de la personne
	"last_name" TEXT NOT NULL,
	-- Date de naissance de la personne
	"birthdate" DATE NOT NULL,
	-- Numéro de téléphone de la personne
	"phone_number" TEXT NOT NULL,
	-- Adresse email de la personne
	"email" TEXT NOT NULL UNIQUE,
	-- Status de la personne dans l'organisation
	"status" VARCHAR(40),
	-- L'origine du contact avec la personne
	"contact_origin" CONTACT_ORIGIN NOT NULL,
	-- Adresse postale de la personne 
	"address" VARCHAR(255),
	-- ID de la clée primaire de la commune de la personne
	"municipality_id" INTEGER,
	-- Date de création de la personne dans la base de données
	"creation_date" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("ff2b_id")
);

COMMENT ON COLUMN "persons"."ff2b_id" IS 'Identifiant unique de la personne au sein de l''organisation';
COMMENT ON COLUMN "persons"."first_name" IS 'Prénom de la personne';
COMMENT ON COLUMN "persons"."last_name" IS 'Nom de famille de la personne';
COMMENT ON COLUMN "persons"."birthdate" IS 'Date de naissance de la personne';
COMMENT ON COLUMN "persons"."phone_number" IS 'Numéro de téléphone de la personne';
COMMENT ON COLUMN "persons"."email" IS 'Adresse email de la personne';
COMMENT ON COLUMN "persons"."status" IS 'Status de la personne dans l''organisation';
COMMENT ON COLUMN "persons"."contact_origin" IS 'L''origine du contact avec la personne';
COMMENT ON COLUMN "persons"."address" IS 'Adresse postale de la personne ';
COMMENT ON COLUMN "persons"."municipality_id" IS 'ID de la clée primaire de la commune de la personne';
COMMENT ON COLUMN "persons"."creation_date" IS 'Date de création de la personne dans la base de données';

CREATE TABLE IF NOT EXISTS "person_role" (
	-- ID unique du rôle de la personne
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID du rôle
	"role_id" SMALLINT NOT NULL,
	-- ID de la personne
	"person_id" UUID NOT NULL,
	PRIMARY KEY("id"),
	CONSTRAINT "person_role_unique_0" UNIQUE ("role_id", "person_id")
);

COMMENT ON COLUMN "person_role"."id" IS 'ID unique du rôle de la personne';
COMMENT ON COLUMN "person_role"."role_id" IS 'ID du rôle';
COMMENT ON COLUMN "person_role"."person_id" IS 'ID de la personne';

CREATE TABLE IF NOT EXISTS "roles" (
	-- L'identifiant unique du role
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Le code unique du rôle
	"code" TEXT NOT NULL UNIQUE,
	-- Le texte affiché du rôle dans le système
	"label" TEXT NOT NULL UNIQUE,
	-- Description du rôle
	"description" TEXT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "roles"."id" IS 'L''identifiant unique du role';
COMMENT ON COLUMN "roles"."code" IS 'Le code unique du rôle';
COMMENT ON COLUMN "roles"."label" IS 'Le texte affiché du rôle dans le système';

CREATE TABLE IF NOT EXISTS "licenses" (
	-- ID unique de la licence dans l'organisation
	"id" UUID NOT NULL DEFAULT gen_random_uuid(),
	-- Le type de la licence.
	"license_type" INTEGER NOT NULL,
	-- ID de la personne propriétaire de la licence
	"person_id" UUID NOT NULL,
	-- ID de la saison durant laquelle la licence est valide
	"season_id" INTEGER NOT NULL,
	-- Date de demande de la licence
	"request_date" DATE NOT NULL,
	-- Date de validation de la licence
	"validation_date" DATE,
	-- Date de début de la licence
	"beginning_date" DATE,
	-- Date de fin de validité de la licence
	"end_date" DATE,
	-- Le statut de la licence
	"license_status" LICENCE_STATUS NOT NULL,
	-- ID du document de certificat de la licence
	"document_id" UUID,
	PRIMARY KEY("id"),

	CONSTRAINT validation_date_check CHECK (
    "validation_date" IS NULL
    OR "validation_date" >= "request_date"
),
	CONSTRAINT end_date_check CHECK (
    "end_date" IS NULL
    OR "beginning_date" IS NULL
    OR "end_date" >= "beginning_date"
)
);

COMMENT ON COLUMN "licenses"."id" IS 'ID unique de la licence dans l''organisation';
COMMENT ON COLUMN "licenses"."license_type" IS 'Le type de la licence.';
COMMENT ON COLUMN "licenses"."person_id" IS 'ID de la personne propriétaire de la licence';
COMMENT ON COLUMN "licenses"."season_id" IS 'ID de la saison durant laquelle la licence est valide';
COMMENT ON COLUMN "licenses"."request_date" IS 'Date de demande de la licence';
COMMENT ON COLUMN "licenses"."validation_date" IS 'Date de validation de la licence';
COMMENT ON COLUMN "licenses"."beginning_date" IS 'Date de début de la licence';
COMMENT ON COLUMN "licenses"."end_date" IS 'Date de fin de validité de la licence';
COMMENT ON COLUMN "licenses"."license_status" IS 'Le statut de la licence';
COMMENT ON COLUMN "licenses"."document_id" IS 'ID du document de certificat de la licence';

CREATE TABLE IF NOT EXISTS "license_type" (
	-- ID Unique du type de licence
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code du type de licence
	"license_code" TEXT NOT NULL UNIQUE,
	-- Texte affiché du type de licence
	"license_label" TEXT NOT NULL UNIQUE,
	-- Description de la licence
	"description" TEXT NULL,

	PRIMARY KEY("id"),
	CONSTRAINT "license_type_unique_0" UNIQUE ("license_code", "license_label")
);

COMMENT ON COLUMN "license_type"."id" IS 'ID Unique du type de licence';
COMMENT ON COLUMN "license_type"."license_code" IS 'Code du type de licence';
COMMENT ON COLUMN "license_type"."license_label" IS 'Texte affiché du type de licence';

CREATE TABLE IF NOT EXISTS "seasons" (
	-- ID unique de la saison
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Année de début de la saison
	"start_year" SMALLINT NOT NULL,
	-- Année de fin de la saison
	"end_year" SMALLINT NOT NULL CHECK("end_year" = "start_year" + 1),
	PRIMARY KEY("id"),
	CONSTRAINT "seasons_unique_0" UNIQUE ("start_year", "end_year")
);

COMMENT ON COLUMN "seasons"."id" IS 'ID unique de la saison';
COMMENT ON COLUMN "seasons"."start_year" IS 'Année de début de la saison';
COMMENT ON COLUMN "seasons"."end_year" IS 'Année de fin de la saison';

CREATE TABLE IF NOT EXISTS "municipalities" (
	-- ID unique de la commune
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Nom de la commune
	"name" TEXT NOT NULL,
	-- Le code postale de la commune
	"zip_code" TEXT NOT NULL,
	-- Code INSEE de la commune
	"insee_code" VARCHAR(10),
	-- ID du département de la commune
	"departement_id" INTEGER NOT NULL,
	-- Status de développement de la commune
	"development_status" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "municipalities"."id" IS 'ID unique de la commune';
COMMENT ON COLUMN "municipalities"."name" IS 'Nom de la commune';
COMMENT ON COLUMN "municipalities"."zip_code" IS 'Le code postale de la commune';
COMMENT ON COLUMN "municipalities"."insee_code" IS 'Code INSEE de la commune';
COMMENT ON COLUMN "municipalities"."departement_id" IS 'ID du département de la commune';
COMMENT ON COLUMN "municipalities"."development_status" IS 'Status de développement de la commune';

CREATE TABLE IF NOT EXISTS "departments" (
	-- ID du departement
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Nom du département
	"name" TEXT NOT NULL,
	-- Code du département
	"code" TEXT NOT NULL,
	-- ID de la région dans laquelle se trouve la commune
	"region_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "departments"."id" IS 'ID du departement';
COMMENT ON COLUMN "departments"."name" IS 'Nom du département';
COMMENT ON COLUMN "departments"."code" IS 'Code du département';
COMMENT ON COLUMN "departments"."region_id" IS 'ID de la région dans laquelle se trouve la commune';

CREATE TABLE IF NOT EXISTS "regions" (
	-- ID de la région 
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Nom de la région
	"name" TEXT NOT NULL,
	-- Code de la region, si disponible
	"code" TEXT,
	-- ID du pays correspondant
	"country_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "regions"."id" IS 'ID de la région ';
COMMENT ON COLUMN "regions"."name" IS 'Nom de la région';
COMMENT ON COLUMN "regions"."code" IS 'Code de la region, si disponible';
COMMENT ON COLUMN "regions"."country_id" IS 'ID du pays correspondant';

CREATE TABLE IF NOT EXISTS "countries" (
	-- ID du pays
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Le nom du pays
	"name" TEXT NOT NULL,
	-- Code du pays 
	"code" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "countries"."id" IS 'ID du pays';
COMMENT ON COLUMN "countries"."name" IS 'Le nom du pays';
COMMENT ON COLUMN "countries"."code" IS 'Code du pays ';

CREATE TABLE IF NOT EXISTS "practice_site" (
	-- ID du site de pratique
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Nom du site de pratique
	"name" TEXT NOT NULL,
	-- ID de la municipalité
	"municipality_id" INTEGER NOT NULL,
	-- Adresse du site de pratique
	"address" TEXT,
	-- Date d'ouverture du site de pratique
	"opening_date" DATE,
	-- Date de fermeture du site de pratique 
	"closing_date" DATE CHECK (
    closing_date IS NULL
    OR opening_date IS NULL
    OR closing_date >= opening_date
),
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "practice_site"."id" IS 'ID du site de pratique';
COMMENT ON COLUMN "practice_site"."name" IS 'Nom du site de pratique';
COMMENT ON COLUMN "practice_site"."municipality_id" IS 'ID de la municipalité';
COMMENT ON COLUMN "practice_site"."address" IS 'Adresse du site de pratique';
COMMENT ON COLUMN "practice_site"."opening_date" IS 'Date d''ouverture du site de pratique';
COMMENT ON COLUMN "practice_site"."closing_date" IS 'Date de fermeture du site de pratique ';

CREATE TABLE IF NOT EXISTS "slots" (
	-- ID du créneau
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID du site appartenant au créneau
	"site_id" INTEGER NOT NULL,
	-- ID de la saison
	"season_id" INTEGER NOT NULL,
	-- Timestamp de début de créneau
	"start_at" TIME NOT NULL,
	-- Timestamp de fin de créneau
	"end_at" TIME NOT NULL,
	-- Capacité d'effectif
	"capacity" SMALLINT  CHECK ("capacity" > 0),
	-- Le jour du créneau (entre 1 et 7)
	"day_of_week" SMALLINT CHECK(day_of_week BETWEEN 1 AND 7),
	PRIMARY KEY("id"),
	CONSTRAINT slots_unique_0 UNIQUE (
    "site_id",
    "season_id",
    "day_of_week",
    "start_at",
    "end_at"
)
);

COMMENT ON COLUMN "slots"."id" IS 'ID du créneau';
COMMENT ON COLUMN "slots"."site_id" IS 'ID du site appartenant au créneau';
COMMENT ON COLUMN "slots"."season_id" IS 'ID de la saison';
COMMENT ON COLUMN "slots"."start_at" IS 'Timestamp de début de créneau';
COMMENT ON COLUMN "slots"."end_at" IS 'Timestamp de fin de créneau';
COMMENT ON COLUMN "slots"."capacity" IS 'Capacité d''effectif';
COMMENT ON COLUMN "slots"."day_of_week" IS 'Le jour du créneau (entre 1 et 7)';

CREATE TABLE IF NOT EXISTS "sessions" (
	-- ID de la séance
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID du créneau pour la séance
	"slot_id" INTEGER NOT NULL,
	-- Timestamp de début de séance
	"start_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Durée de la séance (en minutes)
	"duration" SMALLINT NOT NULL  CHECK (duration > 0),
	-- ID du référent de la séance
	"referent_id" INTEGER,
	-- ID du coach de la séance
	"coach_id" UUID,
	-- Contenu de la séance
	"content" TEXT,
	-- Statut de la séance
	"status" SEANCE_STATUS,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "sessions"."id" IS 'ID de la séance';
COMMENT ON COLUMN "sessions"."slot_id" IS 'ID du créneau pour la séance';
COMMENT ON COLUMN "sessions"."start_at" IS 'Timestamp de début de séance';
COMMENT ON COLUMN "sessions"."duration" IS 'Durée de la séance (en minutes)';
COMMENT ON COLUMN "sessions"."referent_id" IS 'ID du référent de la séance';
COMMENT ON COLUMN "sessions"."coach_id" IS 'ID du coach de la séance';
COMMENT ON COLUMN "sessions"."content" IS 'Contenu de la séance';
COMMENT ON COLUMN "sessions"."status" IS 'Statut de la séance';

CREATE TABLE IF NOT EXISTS "session_participants" (
	-- ID de combinaison participant séance
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID de la personne
	"person_id" UUID NOT NULL,
	-- ID de la séance
	"session_id" INTEGER NOT NULL,
	-- ID de la licence
	"license_id" UUID NOT NULL,
	-- Valeur enregistrant la présence d'une personne
	"presence" BOOLEAN NULL,
	PRIMARY KEY("id"),
	CONSTRAINT "session_participants_unique_0" UNIQUE ("person_id", "session_id")
);

COMMENT ON COLUMN "session_participants"."id" IS 'ID de combinaison participant séance';
COMMENT ON COLUMN "session_participants"."person_id" IS 'ID de la personne';
COMMENT ON COLUMN "session_participants"."session_id" IS 'ID de la séance';
COMMENT ON COLUMN "session_participants"."license_id" IS 'ID de la licence';
COMMENT ON COLUMN "session_participants"."presence" IS 'Valeur enregistrant la présence d''une personne';

CREATE TABLE IF NOT EXISTS "competitions" (
	-- ID de la compétition
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID de la saison auquel la compétition appartient
	"season_id" INTEGER NOT NULL,
	-- Date de la compétition
	"date" DATE NOT NULL,
	-- Lieu de la compétition
	"location_id" INTEGER NOT NULL,
	-- ID du site de pratique
	"practice_site_id" INTEGER NOT NULL,
	-- ID de l'organisateur
	"organizer_id" UUID NOT NULL,
	-- ID référant au format de la compétition
	"format_id" SMALLINT NOT NULL,
	-- Statut de la compétition
	"status" INTEGER,
	-- Clée étrangère vers le document des règles dans la BDD
	"rules_document_id" UUID,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competitions"."id" IS 'ID de la compétition';
COMMENT ON COLUMN "competitions"."season_id" IS 'ID de la saison auquel la compétition appartient';
COMMENT ON COLUMN "competitions"."date" IS 'Date de la compétition';
COMMENT ON COLUMN "competitions"."location_id" IS 'Lieu de la compétition';
COMMENT ON COLUMN "competitions"."practice_site_id" IS 'ID du site de pratique';
COMMENT ON COLUMN "competitions"."organizer_id" IS 'ID de l''organisateur';
COMMENT ON COLUMN "competitions"."format_id" IS 'ID référant au format de la compétition';
COMMENT ON COLUMN "competitions"."status" IS 'Statut de la compétition';
COMMENT ON COLUMN "competitions"."rules_document_id" IS 'Clée étrangère vers le document des règles dans la BDD';

CREATE TABLE IF NOT EXISTS "competition_format" (
	-- ID du format de compétition
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code du format de compétition
	"code" TEXT NOT NULL UNIQUE,
	-- Texte affiché du format de la compétition
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competition_format"."id" IS 'ID du format de compétition';
COMMENT ON COLUMN "competition_format"."code" IS 'Code du format de compétition';
COMMENT ON COLUMN "competition_format"."label" IS 'Texte affiché du format de la compétition';

CREATE TABLE IF NOT EXISTS "competition_status" (
	-- ID unique du statut de compétition
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code unique du statut de la compétition
	"code" TEXT NOT NULL UNIQUE,
	-- Texte affiché du statut de la compétition
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competition_status"."id" IS 'ID unique du statut de compétition';
COMMENT ON COLUMN "competition_status"."code" IS 'Code unique du statut de la compétition';
COMMENT ON COLUMN "competition_status"."label" IS 'Texte affiché du statut de la compétition';

CREATE TABLE IF NOT EXISTS "competition_participant" (
	-- ID unique de la participation à la compétition
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID de la compétition
	"competition_id" INTEGER NOT NULL,
	-- UUID de la personne
	"person_id" UUID NOT NULL,
	-- Status de la participation à la compétition
	"status" INTEGER NOT NULL,
	-- Catégorie de la participation
	"category" INTEGER NOT NULL,
	-- UUID de la licence du participant
	"license_id" UUID NOT NULL,
	-- Classement avant participation
	"ranking_before" SMALLINT,
	-- Classement après modification
	"ranking_after" SMALLINT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "competition_participant"."id" IS 'ID unique de la participation à la compétition';
COMMENT ON COLUMN "competition_participant"."competition_id" IS 'ID de la compétition';
COMMENT ON COLUMN "competition_participant"."person_id" IS 'UUID de la personne';
COMMENT ON COLUMN "competition_participant"."status" IS 'Status de la participation à la compétition';
COMMENT ON COLUMN "competition_participant"."category" IS 'Catégorie de la participation';
COMMENT ON COLUMN "competition_participant"."license_id" IS 'UUID de la licence du participant';
COMMENT ON COLUMN "competition_participant"."ranking_before" IS 'Classement avant participation';
COMMENT ON COLUMN "competition_participant"."ranking_after" IS 'Classement après modification';

CREATE TABLE IF NOT EXISTS "competition_participant_status" (
	-- ID unique du statut du participant de la compétition
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code unique du statut du participant de la compétition
	"code" TEXT NOT NULL UNIQUE,
	-- Label du statut du participant de la compétition
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id"),
	CONSTRAINT "competition_participant_status_unique_0" UNIQUE ("code", "label")
);

COMMENT ON COLUMN "competition_participant_status"."id" IS 'ID unique du statut du participant de la compétition';
COMMENT ON COLUMN "competition_participant_status"."code" IS 'Code unique du statut du participant de la compétition';
COMMENT ON COLUMN "competition_participant_status"."label" IS 'Label du statut du participant de la compétition';

CREATE TABLE IF NOT EXISTS "competition_participant_category" (
	-- ID de la catégorie du participant de la compétition
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code unique de la catégorie du participant de la compétition
	"code" TEXT NOT NULL UNIQUE,
	-- Label de la catégorie du participant de la compétition
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id"),
	CONSTRAINT "competition_participant_category_unique_0" UNIQUE ("code", "label")
);

COMMENT ON COLUMN "competition_participant_category"."id" IS 'ID de la catégorie du participant de la compétition';
COMMENT ON COLUMN "competition_participant_category"."code" IS 'Code unique de la catégorie du participant de la compétition';
COMMENT ON COLUMN "competition_participant_category"."label" IS 'Label de la catégorie du participant de la compétition';

CREATE TABLE IF NOT EXISTS "games" (
	-- ID du match
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID de la compétition
	"competition_id" INTEGER,
	-- ID du format du match
	"format_id" SMALLINT NOT NULL,
	-- Timestamp du match
	"date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "games"."id" IS 'ID du match';
COMMENT ON COLUMN "games"."competition_id" IS 'ID de la compétition';
COMMENT ON COLUMN "games"."format_id" IS 'ID du format du match';
COMMENT ON COLUMN "games"."date" IS 'Timestamp du match';

CREATE TABLE IF NOT EXISTS "game_format" (
	-- ID du format de match
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code unique du format
	"code" TEXT NOT NULL UNIQUE,
	-- Label unique du format
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "game_format"."id" IS 'ID du format de match';
COMMENT ON COLUMN "game_format"."code" IS 'Code unique du format';
COMMENT ON COLUMN "game_format"."label" IS 'Label unique du format';

CREATE TABLE IF NOT EXISTS "game_participant" (
	-- ID de la participation à la partie
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID du côté du participant
	"game_side_id" INTEGER NOT NULL,
	-- Classement avant participation
	"ranking_before" SMALLINT NOT NULL,
	-- Classement après le match
	"ranking_after" SMALLINT,
	-- ELO avant match
	"elo_before" SMALLINT CHECK ("elo_before" > 0),
	-- ELO après match
	"elo_after" SMALLINT  CHECK ("elo_after" > 0),
	-- ID de la personne
	"person_id" UUID NOT NULL,

	

	PRIMARY KEY("id")
);

COMMENT ON COLUMN "game_participant"."id" IS 'ID de la participation à la partie';
COMMENT ON COLUMN "game_participant"."game_side_id" IS 'ID du côté du participant';
COMMENT ON COLUMN "game_participant"."ranking_before" IS 'Classement avant participation';
COMMENT ON COLUMN "game_participant"."ranking_after" IS 'Classement après le match';
COMMENT ON COLUMN "game_participant"."elo_before" IS 'ELO avant match';
COMMENT ON COLUMN "game_participant"."elo_after" IS 'ELO après match';
COMMENT ON COLUMN "game_participant"."person_id" IS 'ID de la personne';

CREATE TABLE IF NOT EXISTS "game_side" (
	-- ID du côté du match
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID du match
	"game_id" INTEGER NOT NULL,
	-- Le numéro du côté du match (1, 2)
	"side_number" SMALLINT NOT NULL CHECK("side_number" IN (1, 2)),
	PRIMARY KEY("id"),
	CONSTRAINT "game_side_unique_0" UNIQUE ("game_id", "side_number")
);

COMMENT ON COLUMN "game_side"."id" IS 'ID du côté du match';
COMMENT ON COLUMN "game_side"."game_id" IS 'ID du match';
COMMENT ON COLUMN "game_side"."side_number" IS 'Le numéro du côté du match (1, 2)';

CREATE TABLE IF NOT EXISTS "game_side_result" (
	-- ID du résultat d'un côté du match
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID du côté du match
	"game_side_id" INTEGER NOT NULL UNIQUE,
	-- La valeur de nieshs marqué
	"nieshs_scored" SMALLINT NOT NULL CHECK ("nieshs_scored" >= 0),
	-- La valeur de nieshs concédé
	"nieshs_conceded" SMALLINT NOT NULL CHECK ("nieshs_conceded" >= 0),
	-- Le résultat du côté du match
	"result" SMALLINT NOT NULL CHECK ("result" >= 0),
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "game_side_result"."id" IS 'ID du résultat d''un côté du match';
COMMENT ON COLUMN "game_side_result"."game_side_id" IS 'ID du côté du match';
COMMENT ON COLUMN "game_side_result"."nieshs_scored" IS 'La valeur de nieshs marqué';
COMMENT ON COLUMN "game_side_result"."nieshs_conceded" IS 'La valeur de nieshs concédé';
COMMENT ON COLUMN "game_side_result"."result" IS 'Le résultat du côté du match';

CREATE TABLE IF NOT EXISTS "team" (
	-- ID unique de l'équipe
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID de la compétition dans laquelle l'équipe est inscrite 
	"competition_id" INTEGER NOT NULL,
	-- Nom de l'équipe
	"name" TEXT NOT NULL,
	PRIMARY KEY("id"),
	CONSTRAINT "team_unique_0" UNIQUE ("competition_id", "name")
);

COMMENT ON COLUMN "team"."id" IS 'ID unique de l''équipe';
COMMENT ON COLUMN "team"."competition_id" IS 'ID de la compétition dans laquelle l''équipe est inscrite ';
COMMENT ON COLUMN "team"."name" IS 'Nom de l''équipe';

CREATE TABLE IF NOT EXISTS "team_members" (
	-- ID de l'équipe
	"team_id" INTEGER NOT NULL,
	-- UUID du membre de l'équipe
	"person_id" UUID NOT NULL,
	PRIMARY KEY("team_id", "person_id"),
	CONSTRAINT "team_members_unique_0" UNIQUE ("team_id", "person_id")
);

COMMENT ON COLUMN "team_members"."team_id" IS 'ID de l''équipe';
COMMENT ON COLUMN "team_members"."person_id" IS 'UUID du membre de l''équipe';

CREATE TABLE IF NOT EXISTS "referents" (
	-- ID du référent
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- UUID de la personne
	"person_id" UUID NOT NULL,
	-- ID du site de pratique
	"site_id" INTEGER NOT NULL,
	-- Date de début de rôle de référent
	"start_date" DATE NOT NULL,
	-- Date de fin de référent
	"end_date" DATE CHECK (
    "end_date" IS NULL
    OR "end_date" >= "start_date"
),
	-- Numéro de téléphone professionnel
	"professional_phone" TEXT NOT NULL,
	-- Adresse mail professionnelle du référent
	"professional_mail" TEXT NOT NULL,
	-- Statut du référent dans l'organisation
	"status" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "referents"."id" IS 'ID du référent';
COMMENT ON COLUMN "referents"."person_id" IS 'UUID de la personne';
COMMENT ON COLUMN "referents"."site_id" IS 'ID du site de pratique';
COMMENT ON COLUMN "referents"."start_date" IS 'Date de début de rôle de référent';
COMMENT ON COLUMN "referents"."end_date" IS 'Date de fin de référent';
COMMENT ON COLUMN "referents"."professionnal_phone" IS 'Numéro de téléphone professionnel';
COMMENT ON COLUMN "referents"."professionnal_mail" IS 'Adresse mail professionnelle du référent';
COMMENT ON COLUMN "referents"."status" IS 'Statut du référent dans l''organisation';

CREATE TABLE IF NOT EXISTS "referent_status" (
	-- ID du statut de référent
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code du type de référent
	"code" TEXT NOT NULL,
	-- Texte affiché du référent
	"label" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "referent_status"."id" IS 'ID du statut de référent';
COMMENT ON COLUMN "referent_status"."code" IS 'Code du type de référent';
COMMENT ON COLUMN "referent_status"."label" IS 'Texte affiché du référent';

CREATE TABLE IF NOT EXISTS "volunteers" (
	-- ID Unique du volontaire
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- UUID de la personne
	"person_id" UUID NOT NULL,
	-- UUID du manager
	"manager_id" UUID NOT NULL,
	-- Le contenu de la mission à effectuer
	"mission" TEXT,
	-- Les compétences de la personne
	"skills" TEXT,
	-- Contenu de la disponibilité du volontaire
	"availability" TEXT,
	-- ID du la localisation du volontaire
	"location" INTEGER NOT NULL,
	-- Date de demande de volontariat
	"application_date" DATE,
	-- Contenu de l'observation
	"observations" TEXT,
	-- Début de la période de volontariat
	"start_date" DATE NOT NULL,
	-- Fin de la période de volontariat
	"end_date" DATE CHECK (
    "end_date" IS NULL
    OR "end_date" >= "start_date"
),
	-- Tâches effectués par le volontaire
	"tasks" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "volunteers"."id" IS 'ID Unique du volontaire';
COMMENT ON COLUMN "volunteers"."person_id" IS 'UUID de la personne';
COMMENT ON COLUMN "volunteers"."manager_id" IS 'UUID du manager';
COMMENT ON COLUMN "volunteers"."mission" IS 'Le contenu de la mission à effectuer';
COMMENT ON COLUMN "volunteers"."skills" IS 'Les compétences de la personne';
COMMENT ON COLUMN "volunteers"."availability" IS 'Contenu de la disponibilité du volontaire';
COMMENT ON COLUMN "volunteers"."location" IS 'ID du la localisation du volontaire';
COMMENT ON COLUMN "volunteers"."application_date" IS 'Date de demande de volontariat';
COMMENT ON COLUMN "volunteers"."observations" IS 'Contenu de l''observation';
COMMENT ON COLUMN "volunteers"."start_date" IS 'Début de la période de volontariat';
COMMENT ON COLUMN "volunteers"."end_date" IS 'Fin de la période de volontariat';
COMMENT ON COLUMN "volunteers"."tasks" IS 'Tâches effectués par le volontaire';

CREATE TABLE IF NOT EXISTS "organizations" (
	-- ID de l'organisation
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Nom de l'organisation
	"name" TEXT NOT NULL,
	-- ID du type d'organisation
	"organization_type_id" SMALLINT NOT NULL,
	-- ID de la commune dans laquelle se trouve l'organisation
	"municipality_id" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "organizations"."id" IS 'ID de l''organisation';
COMMENT ON COLUMN "organizations"."name" IS 'Nom de l''organisation';
COMMENT ON COLUMN "organizations"."organization_type_id" IS 'ID du type d''organisation';
COMMENT ON COLUMN "organizations"."municipality_id" IS 'ID de la commune dans laquelle se trouve l''organisation';

CREATE TABLE IF NOT EXISTS "organizations_type" (
	-- ID du type de l'organisation
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code du type de l'organisation
	"code" TEXT NOT NULL,
	-- Texte affiché du type de l'organisation
	"label" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "organizations_type"."id" IS 'ID du type de l''organisation';
COMMENT ON COLUMN "organizations_type"."code" IS 'Code du type de l''organisation';
COMMENT ON COLUMN "organizations_type"."label" IS 'Texte affiché du type de l''organisation';

CREATE TABLE IF NOT EXISTS "organizations_contact" (
	-- ID du contact de l'organisation
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID de l'organisation
	"organization_id" INTEGER NOT NULL,
	-- ID du gérant de l'organisation
	"person_id" UUID NOT NULL,
	-- Fonction de la personne contacté
	"function" TEXT,
	-- Date de début du contact
	"start_date" DATE,
	-- Date de fin du contact
	"end_date" DATE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "organizations_contact"."id" IS 'ID du contact de l''organisation';
COMMENT ON COLUMN "organizations_contact"."organization_id" IS 'ID de l''organisation';
COMMENT ON COLUMN "organizations_contact"."person_id" IS 'ID du gérant de l''organisation';
COMMENT ON COLUMN "organizations_contact"."function" IS 'Fonction de la personne contacté';
COMMENT ON COLUMN "organizations_contact"."start_date" IS 'Date de début du contact';
COMMENT ON COLUMN "organizations_contact"."end_date" IS 'Date de fin du contact';

CREATE TABLE IF NOT EXISTS "prospects" (
	-- ID du prospect
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- UUID de la personne 
	"person_id" UUID,
	-- ID de l'organisation
	"organization_id" INTEGER,
	-- Le type de prospect
	"type" TEXT,
	-- Statut de la prospection
	"status" TEXT,
	-- Intérêt du prospect
	"interest" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "prospects"."id" IS 'ID du prospect';
COMMENT ON COLUMN "prospects"."person_id" IS 'UUID de la personne ';
COMMENT ON COLUMN "prospects"."organization_id" IS 'ID de l''organisation';
COMMENT ON COLUMN "prospects"."type" IS 'Le type de prospect';
COMMENT ON COLUMN "prospects"."status" IS 'Statut de la prospection';
COMMENT ON COLUMN "prospects"."interest" IS 'Intérêt du prospect';

CREATE TABLE IF NOT EXISTS "contacts" (
	-- ID unique du contact
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID de la personne
	"person_id" UUID,
	-- ID de l'organisation
	"organization_id" INTEGER,
	-- Date du contact
	"contact_at" TIMESTAMPTZ,
	-- ID de la personne responsable au sein de l'association
	"responsible_id" UUID NOT NULL,
	-- Sujet du contact
	"subject" TEXT,
	-- Notes de l'interaction
	"notes" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "contacts"."id" IS 'ID unique du contact';
COMMENT ON COLUMN "contacts"."person_id" IS 'ID de la personne';
COMMENT ON COLUMN "contacts"."organization_id" IS 'ID de l''organisation';
COMMENT ON COLUMN "contacts"."contact_at" IS 'Date du contact';
COMMENT ON COLUMN "contacts"."responsible_id" IS 'ID de la personne responsable au sein de l''association';
COMMENT ON COLUMN "contacts"."subject" IS 'Sujet du contact';
COMMENT ON COLUMN "contacts"."notes" IS 'Notes de l''interaction';

CREATE TABLE IF NOT EXISTS "users" (
	-- ID du l'utilisateur sur les plateformes numériques de l'association
	"id" UUID NOT NULL  DEFAULT gen_random_uuid(),
	-- UUID de la personne 
	"person_id" UUID NOT NULL UNIQUE,
	-- Adresse mail de l'utilisateur sur les plateformes numériques
	"email" TEXT NOT NULL,
	-- Mot de passe hashé de l'utilisateur
	"password" TEXT NOT NULL,
	-- Le status du compte de l'utilisateur 
	"statut" SMALLINT,
	-- La date de création du compte utilisateur
	"creation_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "users"."id" IS 'ID du l''utilisateur sur les plateformes numériques de l''association';
COMMENT ON COLUMN "users"."person_id" IS 'UUID de la personne ';
COMMENT ON COLUMN "users"."email" IS 'Adresse mail de l''utilisateur sur les plateformes numériques';
COMMENT ON COLUMN "users"."password" IS 'Mot de passe hashé de l''utilisateur';
COMMENT ON COLUMN "users"."statut" IS 'Le status du compte de l''utilisateur ';
COMMENT ON COLUMN "users"."creation_date" IS 'La date de création du compte utilisateur';

CREATE TABLE IF NOT EXISTS "access_roles" (
	-- ID unique du rôle
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code du rôle
	"code" TEXT NOT NULL UNIQUE,
	-- Texte affiché du rôle
	"label" TEXT NOT NULL UNIQUE,
	-- Description du rôle d'accès
	"description" TEXT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "access_roles"."id" IS 'ID unique du rôle';
COMMENT ON COLUMN "access_roles"."code" IS 'Code du rôle';
COMMENT ON COLUMN "access_roles"."label" IS 'Texte affiché du rôle';

CREATE TABLE IF NOT EXISTS "users_roles" (
	-- ID du rôle
	"role_id" INTEGER NOT NULL,
	-- ID de l'utilisateur
	"user_id" UUID NOT NULL,
	PRIMARY KEY("role_id", "user_id"),
	CONSTRAINT "users_roles_unique_0" UNIQUE ("role_id", "user_id")
);

COMMENT ON COLUMN "users_roles"."role_id" IS 'ID du rôle';
COMMENT ON COLUMN "users_roles"."user_id" IS 'ID de l''utilisateur';

CREATE TABLE IF NOT EXISTS "consents" (
	-- ID du consentement
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- UUID de la personne
	"person_id" UUID NOT NULL,
	-- Le type de consentement
	"consent_type_id" INTEGER NOT NULL,
	-- La date de l'accord donné par la personne
	"given_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Valeur d'acceptation de la personne
	"is_accepted" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "consents"."id" IS 'ID du consentement';
COMMENT ON COLUMN "consents"."person_id" IS 'UUID de la personne';
COMMENT ON COLUMN "consents"."consent_type_id" IS 'Le type de consentement';
COMMENT ON COLUMN "consents"."given_at" IS 'La date de l''accord donné par la personne';
COMMENT ON COLUMN "consents"."is_accepted" IS 'Valeur d''acceptation de la personne';

CREATE TABLE IF NOT EXISTS "consents_type" (
	-- ID unique du type de consentement
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code unique du type de consentement
	"code" TEXT NOT NULL UNIQUE,
	-- Texte affiché du type de consentement
	"label" TEXT NOT NULL,
	-- Description du type de consentement
	"description" TEXT,
	-- Champ pour savoir si l'acceptation est obligatoire pour s'inscrire
	"is_mandatory" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "consents_type"."id" IS 'ID unique du type de consentement';
COMMENT ON COLUMN "consents_type"."code" IS 'Code unique du type de consentement';
COMMENT ON COLUMN "consents_type"."label" IS 'Texte affiché du type de consentement';
COMMENT ON COLUMN "consents_type"."description" IS 'Description du type de consentement';
COMMENT ON COLUMN "consents_type"."is_mandatory" IS 'Champ pour savoir si l''acceptation est obligatoire pour s''inscrire';

CREATE TABLE IF NOT EXISTS "documents" (
	-- ID Unique du document
	"id" UUID NOT NULL DEFAULT gen_random_uuid(),
	-- Le nom du fichier
	"filename" TEXT NOT NULL,
	-- Le lien du fichier sur la plateforme de stockage
	"storage_path" TEXT NOT NULL,
	-- ID du type de document 
	"document_type_id" SMALLINT NOT NULL,
	-- Date d'enregistrement du document dans la base de données
	"creation_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Le type applicatif du document
	"mime_type" VARCHAR(40),
	-- La taille du fichier
	"file_size" INTEGER NOT NULL,
	-- Le hash du fichier
	"hash" VARCHAR(64) NOT NULL,
	-- L'UUID de la personne qui a uploadé le fichier
	"uploaded_by" UUID,
	-- La date d'expiration du document (si dispo)
	"expires_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "documents"."id" IS 'ID Unique du document';
COMMENT ON COLUMN "documents"."filename" IS 'Le nom du fichier';
COMMENT ON COLUMN "documents"."storage_path" IS 'Le lien du fichier sur la plateforme de stockage';
COMMENT ON COLUMN "documents"."document_type_id" IS 'ID du type de document ';
COMMENT ON COLUMN "documents"."creation_date" IS 'Date d''enregistrement du document dans la base de données';
COMMENT ON COLUMN "documents"."mime_type" IS 'Le type applicatif du document';
COMMENT ON COLUMN "documents"."file_size" IS 'La taille du fichier';
COMMENT ON COLUMN "documents"."hash" IS 'Le hash du fichier';
COMMENT ON COLUMN "documents"."uploaded_by" IS 'L''UUID de la personne qui a uploadé le fichier';
COMMENT ON COLUMN "documents"."expires_at" IS 'La date d''expiration du document (si dispo)';

CREATE TABLE IF NOT EXISTS "document_type" (
	-- ID du type de document 
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Le code du type de document dans la base de données
	"document_code" TEXT NOT NULL UNIQUE,
	-- Le texte affiché dans les applications
	"document_label" TEXT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "document_type"."id" IS 'ID du type de document ';
COMMENT ON COLUMN "document_type"."document_code" IS 'Le code du type de document dans la base de données';
COMMENT ON COLUMN "document_type"."document_label" IS 'Le texte affiché dans les applications';

CREATE TABLE IF NOT EXISTS "documents_persons" (
	-- UUID du document
	"document_id" UUID NOT NULL,
	-- UUID de la personne
	"person_id" UUID NOT NULL,
	PRIMARY KEY("document_id", "person_id"),
	CONSTRAINT "documents_persons_unique_0" UNIQUE ("document_id", "person_id")
);

COMMENT ON COLUMN "documents_persons"."document_id" IS 'UUID du document';
COMMENT ON COLUMN "documents_persons"."person_id" IS 'UUID de la personne';

CREATE TABLE IF NOT EXISTS "documents_competitions" (
	-- UUID du document
	"document_id" UUID NOT NULL,
	-- UUID de la compétition
	"competition_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "competition_id"),
	CONSTRAINT "documents_competitions_unique_0" UNIQUE ("document_id", "competition_id")
);

COMMENT ON COLUMN "documents_competitions"."document_id" IS 'UUID du document';
COMMENT ON COLUMN "documents_competitions"."competition_id" IS 'UUID de la compétition';

CREATE TABLE IF NOT EXISTS "documents_licenses" (
	-- UUID du document
	"document_id" UUID NOT NULL,
	-- UUID de la licence
	"license_id" UUID NOT NULL,
	PRIMARY KEY("document_id", "license_id"),
	CONSTRAINT "documents_licenses_unique_0" UNIQUE ("document_id", "license_id")
);

COMMENT ON COLUMN "documents_licenses"."document_id" IS 'UUID du document';
COMMENT ON COLUMN "documents_licenses"."license_id" IS 'UUID de la licence';

CREATE TABLE IF NOT EXISTS "documents_projects" (
	-- UUID du document
	"document_id" UUID NOT NULL,
	-- ID du projet
	"project_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "project_id"),
	CONSTRAINT "documents_projects_unique_0" UNIQUE ("document_id", "project_id")
);

COMMENT ON COLUMN "documents_projects"."document_id" IS 'UUID du document';
COMMENT ON COLUMN "documents_projects"."project_id" IS 'ID du projet';

CREATE TABLE IF NOT EXISTS "documents_commissions" (
	-- IUUID du document
	"document_id" UUID NOT NULL,
	-- ID de la commission
	"commission_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "commission_id"),
	CONSTRAINT "documents_commissions_unique_0" UNIQUE ("document_id", "commission_id")
);

COMMENT ON COLUMN "documents_commissions"."document_id" IS 'IUUID du document';
COMMENT ON COLUMN "documents_commissions"."commission_id" IS 'ID de la commission';

CREATE TABLE IF NOT EXISTS "documents_organizations" (
	-- UUID du document
	"document_id" UUID NOT NULL,
	-- ID de l'organisation
	"organization_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "organization_id"),
	CONSTRAINT "documents_organizations_unique_0" UNIQUE ("document_id", "organization_id")
);

COMMENT ON COLUMN "documents_organizations"."document_id" IS 'UUID du document';
COMMENT ON COLUMN "documents_organizations"."organization_id" IS 'ID de l''organisation';

CREATE TABLE IF NOT EXISTS "documents_practices_sites" (
	-- UUID du document
	"document_id" UUID NOT NULL,
	-- ID du site de pratique
	"practice_site_id" INTEGER NOT NULL,
	PRIMARY KEY("document_id", "practice_site_id"),
	CONSTRAINT "documents_practices_sites_unique_0" UNIQUE ("document_id", "practice_site_id")
);

COMMENT ON COLUMN "documents_practices_sites"."document_id" IS 'UUID du document';
COMMENT ON COLUMN "documents_practices_sites"."practice_site_id" IS 'ID du site de pratique';

CREATE TABLE IF NOT EXISTS "projects" (
	-- ID unique du projet
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Nom du projet
	"name" TEXT NOT NULL,
	-- Description du projet
	"description" TEXT,
	-- ID du statut du projet 
	"status" SMALLINT NOT NULL,
	-- Date de début du projet
	"start_date" DATE NOT NULL,
	-- Date de fin du projet
	"end_date" DATE CHECK (
    "end_date" IS NULL
    OR "end_date" >= "start_date"
),
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "projects"."id" IS 'ID unique du projet';
COMMENT ON COLUMN "projects"."name" IS 'Nom du projet';
COMMENT ON COLUMN "projects"."description" IS 'Description du projet';
COMMENT ON COLUMN "projects"."status" IS 'ID du statut du projet ';
COMMENT ON COLUMN "projects"."start_date" IS 'Date de début du projet';
COMMENT ON COLUMN "projects"."end_date" IS 'Date de fin du projet';

CREATE TABLE IF NOT EXISTS "projects_members" (
	-- ID du projet
	"project_id" INTEGER NOT NULL,
	-- UUID de la personne
	"person_id" UUID NOT NULL,
	-- ID du rôle de la personne dans le projet
	"project_role" INTEGER NOT NULL,
	-- Date à laquelle le membre à rejoint le projet
	"joined_at" DATE,
	PRIMARY KEY("project_id", "person_id"),
	CONSTRAINT "projects_members_unique_0" UNIQUE ("project_id", "person_id")
);

COMMENT ON COLUMN "projects_members"."project_id" IS 'ID du projet';
COMMENT ON COLUMN "projects_members"."person_id" IS 'UUID de la personne';
COMMENT ON COLUMN "projects_members"."project_role" IS 'ID du rôle de la personne dans le projet';
COMMENT ON COLUMN "projects_members"."joined_at" IS 'Date à laquelle le membre à rejoint le projet';

CREATE TABLE IF NOT EXISTS "project_members_role" (
	-- ID du rôle de projet
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code unique du rôle du projet
	"code" TEXT NOT NULL UNIQUE,
	-- Label du rôle de projet
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "project_members_role"."id" IS 'ID du rôle de projet';
COMMENT ON COLUMN "project_members_role"."code" IS 'Code unique du rôle du projet';
COMMENT ON COLUMN "project_members_role"."label" IS 'Label du rôle de projet';

CREATE TABLE IF NOT EXISTS "projects_status" (
	-- ID du statut du projet
	"id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code du statut du projet
	"code" TEXT NOT NULL UNIQUE,
	-- Label du statut du projet
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "projects_status"."id" IS 'ID du statut du projet';
COMMENT ON COLUMN "projects_status"."code" IS 'Code du statut du projet';
COMMENT ON COLUMN "projects_status"."label" IS 'Label du statut du projet';

CREATE TABLE IF NOT EXISTS "commissions" (
	-- ID de la commission
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Nom de la commission
	"name" TEXT NOT NULL,
	-- Code de la commission
	"code" TEXT NOT NULL UNIQUE,
	-- Description de la commission
	"description" TEXT,
	-- UUID du président de la commission
	"president_id" UUID NOT NULL,
	-- Date de création de la commission
	"creation_date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "commissions"."id" IS 'ID de la commission';
COMMENT ON COLUMN "commissions"."name" IS 'Nom de la commission';
COMMENT ON COLUMN "commissions"."code" IS 'Code de la commission';
COMMENT ON COLUMN "commissions"."description" IS 'Description de la commission';
COMMENT ON COLUMN "commissions"."president_id" IS 'UUID du président de la commission';
COMMENT ON COLUMN "commissions"."creation_date" IS 'Date de création de la commission';

CREATE TABLE IF NOT EXISTS "commissions_members" (
	-- ID de la commission
	"commission_id" INTEGER NOT NULL,
	-- ID du membre de la commission
	"person_id" UUID NOT NULL,
	-- Date à laquelle le membre à joint la commission
	"joined_at" DATE NOT NULL,
	PRIMARY KEY("commission_id", "person_id"),
	CONSTRAINT "commissions_members_unique_0" UNIQUE ("commission_id", "person_id")
);

COMMENT ON COLUMN "commissions_members"."commission_id" IS 'ID de la commission';
COMMENT ON COLUMN "commissions_members"."person_id" IS 'ID du membre de la commission';
COMMENT ON COLUMN "commissions_members"."joined_at" IS 'Date à laquelle le membre à joint la commission';

CREATE TABLE IF NOT EXISTS "payments" (
	-- ID du paiement
	"id" UUID NOT NULL  DEFAULT gen_random_uuid(),
	-- UUID de la personne
	"person_id" UUID NOT NULL,
	-- UUID de la licence
	"license_id" UUID NOT NULL,
	-- Le montant du paiement
	"amount" NUMERIC(8,2) NOT NULL,
	"currency" VARCHAR(3) NOT NULL,
	-- Méthode de paiement
	"payment_method" PAYMENTS_METHOD NOT NULL,
	-- Statut du paiement
	"payment_status" PAYMENTS_STATUS NOT NULL,
	-- Date du paiement
	"payment_date" TIMESTAMPTZ NOT NULL,
	-- Référence de la transaction
	"transaction_reference" TEXT NOT NULL UNIQUE,
	-- UUID du document de facture
	"invoice_document" UUID,
	-- Notes sur le paiement
	"notes" TEXT,
	-- Date de création du paiement
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Date de mise à jour du paiement
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "payments"."id" IS 'ID du paiement';
COMMENT ON COLUMN "payments"."person_id" IS 'UUID de la personne';
COMMENT ON COLUMN "payments"."license_id" IS 'UUID de la licence';
COMMENT ON COLUMN "payments"."amount" IS 'Le montant du paiement';
COMMENT ON COLUMN "payments"."payment_method" IS 'Méthode de paiement';
COMMENT ON COLUMN "payments"."payment_status" IS 'Statut du paiement';
COMMENT ON COLUMN "payments"."payment_date" IS 'Date du paiement';
COMMENT ON COLUMN "payments"."transaction_reference" IS 'Référence de la transaction';
COMMENT ON COLUMN "payments"."invoice_document" IS 'UUID du document de facture';
COMMENT ON COLUMN "payments"."notes" IS 'Notes sur le paiement';
COMMENT ON COLUMN "payments"."created_at" IS 'Date de création du paiement';
COMMENT ON COLUMN "payments"."updated_at" IS 'Date de mise à jour du paiement';

CREATE TABLE IF NOT EXISTS "payments_history" (
	-- ID de l'historique
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ID du paiement
	"payment_id" UUID NOT NULL,
	-- Statut précédent
	"previous_status" PAYMENTS_STATUS NOT NULL,
	-- Nouveau statut
	"new_status" PAYMENTS_STATUS NOT NULL,
	-- UUID de la personne qui à changé le statut
	"changed_by" UUID,
	-- Timestamp du moment du changement
	"changed_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	-- Raison du changement
	"reason" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "payments_history"."id" IS 'ID de l''historique';
COMMENT ON COLUMN "payments_history"."payment_id" IS 'ID du paiement';
COMMENT ON COLUMN "payments_history"."previous_status" IS 'Statut précédent';
COMMENT ON COLUMN "payments_history"."new_status" IS 'Nouveau statut';
COMMENT ON COLUMN "payments_history"."changed_by" IS 'UUID de la personne qui à changé le statut';
COMMENT ON COLUMN "payments_history"."changed_at" IS 'Timestamp du moment du changement';
COMMENT ON COLUMN "payments_history"."reason" IS 'Raison du changement';

CREATE TABLE IF NOT EXISTS "users_status" (
	-- ID unique du statut de l'utilisateur
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- Code unique du statut de l'utilisateur
	"code" TEXT NOT NULL UNIQUE,
	-- Label unique du statut de l'utilisateur
	"label" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id"),
	CONSTRAINT "users_status_unique_0" UNIQUE ("code", "label")
);

COMMENT ON COLUMN "users_status"."id" IS 'ID unique du statut de l''utilisateur';
COMMENT ON COLUMN "users_status"."code" IS 'Code unique du statut de l''utilisateur';
COMMENT ON COLUMN "users_status"."label" IS 'Label unique du statut de l''utilisateur';

CREATE TABLE IF NOT EXISTS "logs" (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    user_id UUID,

    action VARCHAR(10) NOT NULL,

    table_name VARCHAR(100) NOT NULL,

    old_data JSONB,

    new_data JSONB,

    CONSTRAINT logs_user_fk
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE SET NULL,

    CONSTRAINT logs_action_check
        CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);

ALTER TABLE "competitions"
ADD FOREIGN KEY("season_id") REFERENCES "seasons"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "licenses"
ADD FOREIGN KEY("season_id") REFERENCES "seasons"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "practice_site"
ADD FOREIGN KEY("municipality_id") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competitions"
ADD FOREIGN KEY("location_id") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competitions"
ADD FOREIGN KEY("practice_site_id") REFERENCES "practice_site"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competitions"
ADD FOREIGN KEY("organizer_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competitions"
ADD FOREIGN KEY("format_id") REFERENCES "competition_format"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "games"
ADD FOREIGN KEY("competition_id") REFERENCES "competitions"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "games"
ADD FOREIGN KEY("format_id") REFERENCES "game_format"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "team"
ADD FOREIGN KEY("competition_id") REFERENCES "competitions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "team_members"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "team_members"
ADD FOREIGN KEY("team_id") REFERENCES "team"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "game_side"
ADD FOREIGN KEY("game_id") REFERENCES "games"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "game_side_result"
ADD FOREIGN KEY("game_side_id") REFERENCES "game_side"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("license_id") REFERENCES "licenses"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "game_participant"
ADD FOREIGN KEY("game_side_id") REFERENCES "game_side"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "game_participant"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "users"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "licenses"
ADD FOREIGN KEY("license_type") REFERENCES "license_type"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "slots"
ADD FOREIGN KEY("site_id") REFERENCES "practice_site"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "slots"
ADD FOREIGN KEY("season_id") REFERENCES "seasons"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "referents"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "referents"
ADD FOREIGN KEY("site_id") REFERENCES "practice_site"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "sessions"
ADD FOREIGN KEY("slot_id") REFERENCES "slots"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "sessions"
ADD FOREIGN KEY("referent_id") REFERENCES "referents"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "session_participants"
ADD FOREIGN KEY("session_id") REFERENCES "sessions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "session_participants"
ADD FOREIGN KEY("license_id") REFERENCES "licenses"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "session_participants"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "volunteers"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "volunteers"
ADD FOREIGN KEY("manager_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "volunteers"
ADD FOREIGN KEY("location") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "contacts"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "contacts"
ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "contacts"
ADD FOREIGN KEY("responsible_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "users_roles"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "prospects"
ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "organizations_contact"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "person_role"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "persons"
ADD FOREIGN KEY("municipality_id") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "person_role"
ADD FOREIGN KEY("role_id") REFERENCES "roles"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("competition_id") REFERENCES "competitions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents"
ADD FOREIGN KEY("document_type_id") REFERENCES "document_type"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "licenses"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "municipalities"
ADD FOREIGN KEY("departement_id") REFERENCES "departments"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "departments"
ADD FOREIGN KEY("region_id") REFERENCES "regions"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "regions"
ADD FOREIGN KEY("country_id") REFERENCES "countries"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "referents"
ADD FOREIGN KEY("status") REFERENCES "referent_status"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "organizations"
ADD FOREIGN KEY("organization_type_id") REFERENCES "organizations_type"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "users_roles"
ADD FOREIGN KEY("role_id") REFERENCES "access_roles"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "prospects"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "organizations"
ADD FOREIGN KEY("municipality_id") REFERENCES "municipalities"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "organizations_contact"
ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "competitions"
ADD FOREIGN KEY("rules_document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "licenses"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "consents"
ADD FOREIGN KEY("consent_type_id") REFERENCES "consents_type"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "consents"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "documents"
ADD FOREIGN KEY("uploaded_by") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "competitions"
ADD FOREIGN KEY("status") REFERENCES "competition_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "documents_persons"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_practices_sites"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_commissions"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_projects"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_competitions"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_licenses"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_organizations"
ADD FOREIGN KEY("document_id") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_organizations"
ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_competitions"
ADD FOREIGN KEY("competition_id") REFERENCES "competitions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_licenses"
ADD FOREIGN KEY("license_id") REFERENCES "licenses"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_persons"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "projects"
ADD FOREIGN KEY("status") REFERENCES "projects_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "projects_members"
ADD FOREIGN KEY("project_id") REFERENCES "projects"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "projects_members"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "projects_members"
ADD FOREIGN KEY("project_role") REFERENCES "project_members_role"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "documents_projects"
ADD FOREIGN KEY("project_id") REFERENCES "projects"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "commissions"
ADD FOREIGN KEY("president_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "commissions_members"
ADD FOREIGN KEY("commission_id") REFERENCES "commissions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "commissions_members"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "documents_commissions"
ADD FOREIGN KEY("commission_id") REFERENCES "commissions"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("category") REFERENCES "competition_participant_category"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "competition_participant"
ADD FOREIGN KEY("status") REFERENCES "competition_participant_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "payments_history"
ADD FOREIGN KEY("payment_id") REFERENCES "payments"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "payments"
ADD FOREIGN KEY("invoice_document") REFERENCES "documents"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "payments"
ADD FOREIGN KEY("person_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "payments"
ADD FOREIGN KEY("license_id") REFERENCES "licenses"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "documents_practices_sites"
ADD FOREIGN KEY("practice_site_id") REFERENCES "practice_site"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "sessions"
ADD FOREIGN KEY("coach_id") REFERENCES "persons"("ff2b_id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "users"
ADD FOREIGN KEY("statut") REFERENCES "users_status"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "payments_history"
ADD FOREIGN KEY("changed_by") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;

-- Index

CREATE INDEX IF NOT EXISTS idx_logs_table_changed_at
    ON "logs" ("table_name", "changed_at" DESC);

CREATE INDEX IF NOT EXISTS idx_logs_user_changed_at
    ON "logs" ("user_id", "changed_at" DESC);

CREATE INDEX IF NOT EXISTS idx_logs_action
    ON "logs" ("action");

CREATE INDEX IF NOT EXISTS idx_logs_old_data_gin
    ON "logs"
    USING GIN ("old_data");

CREATE INDEX IF NOT EXISTS idx_logs_new_data_gin
    ON "logs"
    USING GIN ("new_data");

CREATE INDEX IF NOT EXISTS idx_persons_municipality_id
    ON persons (municipality_id);

CREATE INDEX IF NOT EXISTS idx_persons_last_name
    ON persons (last_name);

CREATE INDEX IF NOT EXISTS idx_persons_birthdate
    ON persons (birthdate);


CREATE INDEX IF NOT EXISTS idx_person_role_person_id
    ON person_role (person_id);

CREATE INDEX IF NOT EXISTS idx_licenses_license_type
    ON licenses (license_type);

CREATE INDEX IF NOT EXISTS idx_licenses_person_id
    ON licenses (person_id);

CREATE INDEX IF NOT EXISTS idx_licenses_season
    ON licenses (season_id);

CREATE INDEX IF NOT EXISTS idx_licenses_document_id
    ON licenses (document_id);

CREATE INDEX IF NOT EXISTS idx_licenses_license_status
    ON licenses (license_status);

CREATE INDEX IF NOT EXISTS idx_licenses_end_date
    ON licenses (end_date);

CREATE INDEX IF NOT EXISTS idx_licenses_request_date
    ON licenses (request_date);

CREATE INDEX IF NOT EXISTS idx_licenses_person_season
    ON licenses (person_id, season_id);


CREATE INDEX IF NOT EXISTS idx_license_type_license_code
    ON license_type (license_code);


CREATE INDEX IF NOT EXISTS idx_municipalities_departements_id
    ON municipalities (departement_id);

CREATE INDEX IF NOT EXISTS idx_municipalities_name
    ON municipalities (name);

CREATE INDEX IF NOT EXISTS idx_municipalities_insee_code
    ON municipalities (insee_code);


CREATE INDEX IF NOT EXISTS idx_departments_region_id
    ON departments (region_id);

CREATE INDEX IF NOT EXISTS idx_departments_code
    ON departments (code);


CREATE INDEX IF NOT EXISTS idx_regions_country_id
    ON regions (country_id);

CREATE INDEX IF NOT EXISTS idx_regions_code
    ON regions (code);


CREATE INDEX IF NOT EXISTS idx_countries_code
    ON countries (code);


CREATE INDEX IF NOT EXISTS idx_practice_site_municipality_id
    ON practice_site (municipality_id);

CREATE INDEX IF NOT EXISTS idx_practice_site_name
    ON practice_site (name);


CREATE INDEX IF NOT EXISTS idx_slots_site_id
    ON slots (site_id);

CREATE INDEX IF NOT EXISTS idx_slots_season_id
    ON slots (season_id);

CREATE INDEX IF NOT EXISTS idx_slots_site_season
    ON slots (site_id, season_id);

CREATE INDEX IF NOT EXISTS idx_slots_day_of_week
    ON slots (day_of_week);


CREATE INDEX IF NOT EXISTS idx_sessions_slot_id
    ON sessions (slot_id);

CREATE INDEX IF NOT EXISTS idx_sessions_referent_id
    ON sessions (referent_id);

CREATE INDEX IF NOT EXISTS idx_sessions_coach_id
    ON sessions (coach_id);

CREATE INDEX IF NOT EXISTS idx_sessions_start_time
    ON sessions (start_at);

CREATE INDEX IF NOT EXISTS idx_sessions_status
    ON sessions (status);

CREATE INDEX IF NOT EXISTS idx_sessions_slot_start_time
    ON sessions (slot_id, start_at);


CREATE INDEX IF NOT EXISTS idx_session_participants_session_id
    ON session_participants (session_id);

CREATE INDEX IF NOT EXISTS idx_session_participants_license_id
    ON session_participants (license_id);


CREATE INDEX IF NOT EXISTS idx_competitions_season_id
    ON competitions (season_id);

CREATE INDEX IF NOT EXISTS idx_competitions_location_id
    ON competitions (location_id);

CREATE INDEX IF NOT EXISTS idx_competitions_practice_site_id
    ON competitions (practice_site_id);

CREATE INDEX IF NOT EXISTS idx_competitions_organizer_id
    ON competitions (organizer_id);

CREATE INDEX IF NOT EXISTS idx_competitions_format_id
    ON competitions (format_id);

CREATE INDEX IF NOT EXISTS idx_competitions_status
    ON competitions (status);

CREATE INDEX IF NOT EXISTS idx_competitions_rules_document_id
    ON competitions (rules_document_id);

CREATE INDEX IF NOT EXISTS idx_competitions_date
    ON competitions (date);

CREATE INDEX IF NOT EXISTS idx_competitions_season_date
    ON competitions (season_id, date);


CREATE INDEX IF NOT EXISTS idx_competition_participant_competition_id
    ON competition_participant (competition_id);

CREATE INDEX IF NOT EXISTS idx_competition_participant_person_id
    ON competition_participant (person_id);

CREATE INDEX IF NOT EXISTS idx_competition_participant_status
    ON competition_participant (status);

CREATE INDEX IF NOT EXISTS idx_competition_participant_category
    ON competition_participant (category);

CREATE INDEX IF NOT EXISTS idx_competition_participant_license_id
    ON competition_participant (license_id);

CREATE INDEX IF NOT EXISTS idx_competition_participant_competition_person
    ON competition_participant (competition_id, person_id);


CREATE INDEX IF NOT EXISTS idx_games_competition_id
    ON games (competition_id);

CREATE INDEX IF NOT EXISTS idx_games_format_id
    ON games (format_id);

CREATE INDEX IF NOT EXISTS idx_games_date
    ON games (date);

CREATE INDEX IF NOT EXISTS idx_games_competition_date
    ON games (competition_id, date);


CREATE INDEX IF NOT EXISTS idx_game_participant_game_side_id
    ON game_participant (game_side_id);

CREATE INDEX IF NOT EXISTS idx_game_participant_person_id
    ON game_participant (person_id);


CREATE INDEX IF NOT EXISTS idx_team_members_person_id
    ON team_members (person_id);


CREATE INDEX IF NOT EXISTS idx_referents_person_id
    ON referents (person_id);

CREATE INDEX IF NOT EXISTS idx_referents_site_id
    ON referents (site_id);

CREATE INDEX IF NOT EXISTS idx_referents_status
    ON referents (status);

CREATE INDEX IF NOT EXISTS idx_referents_site_start_date
    ON referents (site_id, start_date);


CREATE INDEX IF NOT EXISTS idx_volunteers_person_id
    ON volunteers (person_id);

CREATE INDEX IF NOT EXISTS idx_volunteers_manager_id
    ON volunteers (manager_id);

CREATE INDEX IF NOT EXISTS idx_volunteers_location
    ON volunteers (location);

CREATE INDEX IF NOT EXISTS idx_volunteers_start_date
    ON volunteers (start_date);

CREATE INDEX IF NOT EXISTS idx_volunteers_end_date
    ON volunteers (end_date);


CREATE INDEX IF NOT EXISTS idx_organizations_organization_type_id
    ON organizations (organization_type_id);

CREATE INDEX IF NOT EXISTS idx_organizations_municipality_id
    ON organizations (municipality_id);

CREATE INDEX IF NOT EXISTS idx_organizations_name
    ON organizations (name);


CREATE INDEX IF NOT EXISTS idx_organizations_contact_organization_id
    ON organizations_contact (organization_id);

CREATE INDEX IF NOT EXISTS idx_organizations_contact_person_id
    ON organizations_contact (person_id);


CREATE INDEX IF NOT EXISTS idx_prospects_person_id
    ON prospects (person_id);

CREATE INDEX IF NOT EXISTS idx_prospects_organization_id
    ON prospects (organization_id);

CREATE INDEX IF NOT EXISTS idx_prospects_type
    ON prospects (type);

CREATE INDEX IF NOT EXISTS idx_prospects_status
    ON prospects (status);


CREATE INDEX IF NOT EXISTS idx_contacts_person_id
    ON contacts (person_id);

CREATE INDEX IF NOT EXISTS idx_contacts_organization_id
    ON contacts (organization_id);

CREATE INDEX IF NOT EXISTS idx_contacts_responsible_id
    ON contacts (responsible_id);

CREATE INDEX IF NOT EXISTS idx_contacts_date
    ON contacts (contact_at);

CREATE INDEX IF NOT EXISTS idx_contacts_responsible_date
    ON contacts (responsible_id, contact_at);


CREATE INDEX IF NOT EXISTS idx_users_person_id
    ON users (person_id);

CREATE INDEX IF NOT EXISTS idx_users_email
    ON users (email);

CREATE INDEX IF NOT EXISTS idx_users_statut
    ON users (statut);


CREATE INDEX IF NOT EXISTS idx_users_roles_user_id
    ON users_roles (user_id);


CREATE INDEX IF NOT EXISTS idx_consents_person_id
    ON consents (person_id);

CREATE INDEX IF NOT EXISTS idx_consents_consent_type_id
    ON consents (consent_type_id);

CREATE INDEX IF NOT EXISTS idx_consents_person_type
    ON consents (person_id, consent_type_id);

CREATE INDEX IF NOT EXISTS idx_consents_given_at
    ON consents (given_at);


CREATE INDEX IF NOT EXISTS idx_documents_document_type_id
    ON documents (document_type_id);

CREATE INDEX IF NOT EXISTS idx_documents_uploaded_by
    ON documents (uploaded_by);

CREATE INDEX IF NOT EXISTS idx_documents_hash
    ON documents (hash);

CREATE INDEX IF NOT EXISTS idx_documents_creation_date
    ON documents (creation_date);

CREATE INDEX IF NOT EXISTS idx_documents_expires_at
    ON documents (expires_at);


CREATE INDEX IF NOT EXISTS idx_documents_persons_person_id
    ON documents_persons (person_id);


CREATE INDEX IF NOT EXISTS idx_documents_competitions_competition_id
    ON documents_competitions (competition_id);


CREATE INDEX IF NOT EXISTS idx_documents_licenses_license_id
    ON documents_licenses (license_id);


CREATE INDEX IF NOT EXISTS idx_documents_projects_project_id
    ON documents_projects (project_id);


CREATE INDEX IF NOT EXISTS idx_documents_commissions_commission_id
    ON documents_commissions (commission_id);


CREATE INDEX IF NOT EXISTS idx_documents_organizations_organization_id
    ON documents_organizations (organization_id);


CREATE INDEX IF NOT EXISTS idx_documents_practices_sites_practice_site_id
    ON documents_practices_sites (practice_site_id);


CREATE INDEX IF NOT EXISTS idx_projects_status
    ON projects (status);

CREATE INDEX IF NOT EXISTS idx_projects_start_date
    ON projects (start_date);

CREATE INDEX IF NOT EXISTS idx_projects_end_date
    ON projects (end_date);

CREATE INDEX IF NOT EXISTS idx_projects_status_start_date
    ON projects (status, start_date);


CREATE INDEX IF NOT EXISTS idx_projects_members_person_id
    ON projects_members (person_id);

CREATE INDEX IF NOT EXISTS idx_projects_members_project_role
    ON projects_members (project_role);


CREATE INDEX IF NOT EXISTS idx_commissions_president_id
    ON commissions (president_id);

CREATE INDEX IF NOT EXISTS idx_commissions_name
    ON commissions (name);


CREATE INDEX IF NOT EXISTS idx_commissions_members_person_id
    ON commissions_members (person_id);


CREATE INDEX IF NOT EXISTS idx_payments_person_id
    ON payments (person_id);

CREATE INDEX IF NOT EXISTS idx_payments_license_id
    ON payments (license_id);

CREATE INDEX IF NOT EXISTS idx_payments_payment_status
    ON payments (payment_status);

CREATE INDEX IF NOT EXISTS idx_payments_payment_date
    ON payments (payment_date);

CREATE INDEX IF NOT EXISTS idx_payments_person_date
    ON payments (person_id, payment_date);

CREATE INDEX IF NOT EXISTS idx_payments_license_date
    ON payments (license_id, payment_date);


CREATE INDEX IF NOT EXISTS idx_payments_history_payment_id
    ON payments_history (payment_id);

CREATE INDEX IF NOT EXISTS idx_payments_history_changed_by
    ON payments_history (changed_by);

CREATE INDEX IF NOT EXISTS idx_payments_history_changed_at
    ON payments_history (changed_at);

CREATE INDEX IF NOT EXISTS idx_payments_history_payment_changed_at
    ON payments_history (payment_id, changed_at);

